import { callGrok, GROK_SMART } from '@/lib/grok'

/**
 * Content Engine — AI script drafting. New isolated feature; imports only
 * generic, feature-agnostic infra (@/lib/grok, same class of dependency as
 * @/lib/db) — nothing from src/lib/monitor/* is touched or imported.
 *
 * Fixed per-niche template (identity/wardrobe/scene-lock) is NOT generated by
 * the LLM — those are business decisions enforced in code, matching this
 * project's "structural guarantee, not just prompted" pattern. The LLM only
 * writes the joke: scene_events[] + duration_seconds.
 */

export interface Person {
  id: string
  role: string
  appearance: string
  wardrobe: string
}

export interface SceneEvent {
  timestamp: string
  speaker: string // a Person.id, or "none"
  line: string | null
  delivery: string | null
  action: string
}

export interface Script {
  duration_seconds: number
  people: Person[]
  environment: string
  lighting: string
  scene_events: SceneEvent[]
  negative_prompt: string
}

const PEOPLE: Person[] = [
  {
    id: 'female_subject',
    role: 'main subject on camera, sitting in the driver seat of a luxury sports car with the window rolled down',
    appearance: 'identity locked to the reference photos provided as separate images -- same face, hair, skin tone',
    wardrobe: 'red blazer over a white lace top, small earrings',
  },
  {
    id: 'cameraman',
    role: 'interviewer, standing just outside the car window, fully out of frame',
    appearance: 'never visible on screen -- no face, no body, no hands',
    wardrobe: 'n/a -- not in frame',
  },
]
const ENVIRONMENT =
  'Interior of a luxury sports car parked on an upscale Dubai street, palm trees and modern buildings visible through the windshield, bright daylight.'
const LIGHTING = 'Bright, direct natural sunlight illuminating the car interior and her face.'
const NEGATIVE_PROMPT =
  'no smooth gimbal motion, no cinematic stabilization, no professional studio lighting, no beauty filter, ' +
  'no AI skin smoothing, extra fingers, extra limbs, warped hands, morphing face, identity drift, camera zoom, ' +
  'camera pan, camera cut, wardrobe change mid-scene, steering wheel or dashboard moving position, ' +
  'car interior changing, blurry, low resolution, watermark, text overlay'

export const PERSONA = `She is confident, witty, and a little flirty -- deadpan delivery, sarcastic
punchlines, teases the interviewer and her male audience good-naturedly. Humor targets car
brands, driving habits, and client stereotypes (never race, religion, or other protected
traits). Buildup -> short pause/beat if needed -> punchline that lands ON HER, delivered
with a laugh or smirk.`

// Few-shot: real, user-approved examples (their own words).
const STYLE_EXAMPLES = [
  {
    duration_seconds: 8,
    scene_events: [
      { timestamp: '0:00-0:01', speaker: 'cameraman', line: 'Izvini, koja je razlika između vozača BMW-a i prirodne nepogode?', delivery: 'curious, teasing, from outside the car', action: 'She sits relaxed behind the wheel, confident smirk. Mouth closed and still -- only listening.' },
      { timestamp: '0:01-0:02', speaker: 'female_subject', line: 'Nikakva...', delivery: 'calm, deadpan', action: 'Steady eye contact toward the window.' },
      { timestamp: '0:02-0:03', speaker: 'female_subject', line: 'Obe dolaze iznenada...', delivery: 'building the punchline, playful smile', action: 'Leans slightly closer to the window.' },
      { timestamp: '0:03-0:04', speaker: 'none', line: null, delivery: null, action: 'Pauses for effect, mouth closed.' },
      { timestamp: '0:04-0:05', speaker: 'female_subject', line: 'I kod obe se pitaš...', delivery: 'amused, eyebrow raised', action: 'Mocking grin.' },
      { timestamp: '0:05-0:06', speaker: 'female_subject', line: 'Odakle se ovaj stvorio i zašto ne koristi žmigavac?!', delivery: 'sarcastic punchline', action: 'Laughs, head tilts back.' },
      { timestamp: '0:06-0:08', speaker: 'none', line: null, delivery: null, action: 'Relaxed, satisfied smile as the clip ends.' },
    ],
  },
  {
    duration_seconds: 11,
    scene_events: [
      { timestamp: '0:00-0:01.2', speaker: 'cameraman', line: 'Can I ask you something?', delivery: 'friendly, casual', action: 'Relaxed, welcoming smile. Mouth closed and still -- only listening.' },
      { timestamp: '0:01.2-0:01.7', speaker: 'female_subject', line: 'Sure.', delivery: 'warm, quick', action: 'Turns fully toward the window.' },
      { timestamp: '0:01.7-0:02.7', speaker: 'cameraman', line: 'What do you do?', delivery: 'curious', action: 'Confident posture, mouth closed and still, listening.' },
      { timestamp: '0:02.7-0:04.0', speaker: 'female_subject', line: 'I run a rent-a-car agency.', delivery: 'proud, matter-of-fact', action: 'Gestures toward the car interior.' },
      { timestamp: '0:04.0-0:05.8', speaker: 'cameraman', line: 'What surprises you most about your clients?', delivery: 'playful, leaning in', action: 'Eyebrow raised, mouth closed and still, listening.' },
      { timestamp: '0:05.8-0:08.8', speaker: 'female_subject', line: 'Random liquid on the back seat... flowers left behind... a brand new iPhone as a gift.', delivery: 'quick wry list, counting fingers', action: 'Counts on her fingers.' },
      { timestamp: '0:08.8-0:09.8', speaker: 'cameraman', line: 'Why would they do that?', delivery: 'surprised, half-laughing', action: 'Grins, anticipating her punchline, mouth closed and still, listening.' },
      { timestamp: '0:09.8-0:11', speaker: 'female_subject', line: "No idea... they're crazy about blondes, hahaha!", delivery: 'sarcastic punchline, laughing', action: 'Laughs, settles into a satisfied smile as the clip ends.' },
    ],
  },
]

const SYSTEM_PROMPT = `You write short comedic dialogue scripts for a car-rental social media ad
format: a woman sits in the driver's seat of a rental car with the window down, an unseen
interviewer standing outside asks her things, she answers with a joke/punchline.

PERSONA: ${PERSONA}

OUTPUT FORMAT: a single JSON object with exactly two keys:
{
  "duration_seconds": <number>,
  "scene_events": [
    { "timestamp": "0:00-0:01.2", "speaker": "cameraman" | "female_subject" | "none",
      "line": "<spoken words, or null>", "delivery": "<tone/manner, or null>",
      "action": "<physical action/expression at this beat -- always present>" }
  ]
}

RULES:
1. "speaker" must be exactly "cameraman", "female_subject", or "none" -- nothing else.
2. Timestamps are contiguous and increasing, starting at "0:00", ending exactly at
   duration_seconds. No gaps, no overlaps.
3. Realistic speech pace: ~140-170 words per minute total across all spoken lines. Do not
   cram long lines into a short timestamp -- unnaturally fast delivery reads as broken lip
   sync. Compute duration from the actual word count, don't guess.
4. Target total duration 8-13 seconds. Only go longer if the joke genuinely needs it, and
   never exceed 15 seconds.
5. Default to a real back-and-forth: the cameraman should ask a follow-up question or drop a
   reactive remark between her lines, not just fire one opening question and go silent for
   the rest of the clip. A single speaker may hold two consecutive beats only when genuinely
   mid-sentence (e.g. listing items, or a short pause-then-continue) -- never as the default
   shape of the whole script. Aim for at least 2 cameraman turns (opening question + at least
   one follow-up/reaction) on anything 8s or longer.
6. The LAST spoken beat must be "female_subject" delivering the punchline. It's fine to end
   with one final "none" reaction beat after it.
7. Every beat needs an "action" describing her physical performance at that moment (even
   "none" beats). When she is NOT the speaker, her action must make clear she is silently
   listening (e.g. "mouth closed and still, listening") -- she must never appear to be
   speaking during the interviewer's lines.
8. Keep humor about car brands, driving habits, or client behavior -- like the examples.
   Never target race, religion, nationality, or other protected traits.
9. Output ONLY the JSON object. No commentary, no markdown fences.`

interface GrokDraft {
  duration_seconds: number
  scene_events: SceneEvent[]
}

export interface ScriptWarning {
  message: string
}

/** Structural check mirroring the copy-paste-v2 misattribution fix: catches a
 * speaker id the renderer wouldn't recognise before it ever reaches a prompt. */
function validate(draft: GrokDraft): ScriptWarning[] {
  const warnings: ScriptWarning[] = []
  const validSpeakers = new Set(['cameraman', 'female_subject', 'none'])
  for (const e of draft.scene_events) {
    if (!validSpeakers.has(e.speaker)) warnings.push({ message: `Unknown speaker "${e.speaker}" at ${e.timestamp}` })
  }
  const last = draft.scene_events.filter(e => e.line).pop()
  if (!last || last.speaker !== 'female_subject') {
    warnings.push({ message: 'Last spoken line is not female_subject -- punchline may not land on her' })
  }
  const totalWords = draft.scene_events
    .filter(e => e.line)
    .reduce((n, e) => n + (e.line as string).trim().split(/\s+/).length, 0)
  const wpm = totalWords / (draft.duration_seconds / 60)
  if (wpm > 190) warnings.push({ message: `Pacing looks too fast: ~${Math.round(wpm)} wpm (target 140-170)` })
  if (wpm < 100 && totalWords > 3) warnings.push({ message: `Pacing looks too slow: ~${Math.round(wpm)} wpm (target 140-170)` })
  if (draft.duration_seconds > 15) warnings.push({ message: `Duration ${draft.duration_seconds}s exceeds the 15s cap` })
  return warnings
}

export async function generateScript(topic: string): Promise<{ script: Script; warnings: ScriptWarning[] }> {
  if (!topic.trim()) throw new Error('topic is required')

  const userPrompt = `TOPIC / BRIEF: ${topic}

Here are two real, approved examples of the exact format and style (for reference only,
write a NEW script, don't reuse these):

EXAMPLE 1 -- a short clip where she carries the build-up alone after one question. This is
the EXCEPTION, only for a tight joke that doesn't need a follow-up:
${JSON.stringify(STYLE_EXAMPLES[0], null, 2)}

EXAMPLE 2 -- a real back-and-forth with multiple cameraman turns. This is the DEFAULT shape
to match unless the joke is genuinely too short for it:
${JSON.stringify(STYLE_EXAMPLES[1], null, 2)}

Now write a new script for the topic above.`

  const raw = await callGrok({
    model: GROK_SMART,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
    maxTokens: 2048,
    temperature: 0.9,
    json: true,
    timeoutMs: 120_000,
  })

  const draft: GrokDraft = JSON.parse(raw)
  const warnings = validate(draft)

  const script: Script = {
    duration_seconds: draft.duration_seconds,
    people: PEOPLE,
    environment: ENVIRONMENT,
    lighting: LIGHTING,
    scene_events: draft.scene_events,
    negative_prompt: NEGATIVE_PROMPT,
  }

  return { script, warnings }
}
