ALTER TABLE characters
ADD COLUMN IF NOT EXISTS lora_url TEXT,
ADD COLUMN IF NOT EXISTS lora_scale NUMERIC DEFAULT 0.8,
ADD COLUMN IF NOT EXISTS base_prompt_style TEXT,
ADD COLUMN IF NOT EXISTS story TEXT,
ADD COLUMN IF NOT EXISTS start_date TEXT,
ADD COLUMN IF NOT EXISTS default_mode TEXT DEFAULT 'SFW';

INSERT INTO schema_migrations (name)
VALUES ('009_character_profile_fields')
ON CONFLICT DO NOTHING;