import { nichePrompt, type NicheDefinition } from '@/lib/niche-utils'

/** 25 additional branded niches (~12 prompts each). */
export const EXTRA_NICHE_DEFINITIONS: NicheDefinition[] = [
  {
    id: 'coquette',
    label: 'Coquette',
    description: 'Bows, ribbons, soft pink, romantic feminine, doe eyes, hyper-feminine brand.',
    defaultHairLock: 'long dark hair with bow accessories and soft romantic curls',
    prompts: [
      nichePrompt('in a pink bedroom wearing a white lace camisole and ribbon choker, holding a heart mirror, soft blush makeup and doe-eyed expression'),
      nichePrompt('on a velvet chair in a satin mini dress with bow straps, legs tucked sideways, playing with pearl necklace'),
      nichePrompt('at a bakery counter in a pink gingham dress, holding a macaron box, sweet shy smile'),
      nichePrompt('kneeling on bed in oversized pink cardigan falling off shoulders, lace shorts, writing love note'),
      nichePrompt('in bathroom applying lip gloss, lace robe, bow in hair, soft ring light'),
      nichePrompt('on picnic blanket in white sundress with pink ribbon belt, strawberries and diary nearby'),
      nichePrompt('leaning on piano in corset top and tulle skirt, romantic candle glow'),
      nichePrompt('mirror selfie in pink bathroom, heart pajama set, fluffy slippers'),
      nichePrompt('on balcony at dusk in slip dress and faux fur wrap, holding rose tea cup'),
      nichePrompt('curled on window seat reading romance novel, knee socks and oversized sweater'),
      nichePrompt('at vanity surrounded by ribbons and perfume, lace bralette visible under open blouse'),
      nichePrompt('walking cobblestone street in ballet flats and mini skirt, soft sun on face'),
    ],
  },
  {
    id: 'e-girl',
    label: 'E-Girl',
    description: 'Gaming aesthetic, streak hair, chokers, striped sleeves, LED room, playful energy.',
    defaultHairLock: 'two-tone hair black with bright pink front streaks, winged liner',
    prompts: [
      nichePrompt('at RGB gaming desk wearing striped long sleeve under black tee, choker and chain belt, headset on'),
      nichePrompt('bedroom mirror selfie with LED strips pink and purple, crop top and plaid skirt'),
      nichePrompt('on gaming chair legs up, oversized hoodie and thigh highs, energy drink on desk'),
      nichePrompt('close-up face heavy winged liner and heart stamp under eye, neon sign glow'),
      nichePrompt('streaming setup wave to camera, cat ear headset, playful wink'),
      nichePrompt('convenience store night run, mesh top under jacket, platform sneakers'),
      nichePrompt('lying on bed scrolling phone, fishnet sleeves and shorts, posters on wall'),
      nichePrompt('kitchen making instant ramen, oversized band tee, messy e-girl makeup'),
      nichePrompt('skateboard park sitting on board, striped arm warmers, chain necklace'),
      nichePrompt('bathroom colorful makeup spread, dye-streak hair in clip, playful expression'),
      nichePrompt('arcade claw machine reaching up, cargo pants and crop hoodie'),
      nichePrompt('rainy window gamer mood, blanket and laptop glow on face'),
    ],
  },
  {
    id: 'fitness-baddie',
    label: 'Fitness Baddie',
    description: 'Gym glam, matching sets, squats, protein shakes, athletic confidence.',
    defaultHairLock: 'high ponytail or slick braid, sporty sleek hair',
    prompts: [
      nichePrompt('gym mirror selfie in matching scrunch-butt leggings set, post-workout glow, water bottle in hand'),
      nichePrompt('mid squat rack with barbell, focused expression, hair in high ponytail'),
      nichePrompt('outdoor stair sprint in sports bra and biker shorts, morning sun'),
      nichePrompt('smoothie bar post-workout, tank top and joggers, confident smile'),
      nichePrompt('yoga mat stretch arch back, matching pastel set, studio windows'),
      nichePrompt('locker room bench tying sneaker, defined abs visible, gym bag open'),
      nichePrompt('residential gym cable machine pull, intense eye contact with camera'),
      nichePrompt('track field starting blocks pose, runner aesthetic, wind in ponytail'),
      nichePrompt('protein shake kitchen selfie, oversized gym hoodie open on sports set'),
      nichePrompt('boxing bag mid-punch, hand wraps, fierce athletic energy'),
      nichePrompt('poolside lounge after swim laps, athletic one-piece, wet hair slicked'),
      nichePrompt('sunset rooftop jump rope pause, city backdrop, sweat glow editorial'),
    ],
  },
  {
    id: 'dark-academia',
    label: 'Dark Academia',
    description: 'Tweed, libraries, autumn leaves, vintage glasses, moody scholarly romance.',
    defaultHairLock: 'dark brown hair in low messy bun or loose vintage waves',
    prompts: [
      nichePrompt('in old library aisle stacked books to ceiling, tweed blazer and turtleneck, reading leather volume'),
      nichePrompt('autumn campus bench with coffee and notebook, long coat and scarf, thoughtful gaze'),
      nichePrompt('candlelit desk writing letter, ink pen and wax seal, vest and white shirt'),
      nichePrompt('museum hall marble bust background, long dark skirt and oxford shoes'),
      nichePrompt('rain on Gothic university window, cardigan over slip dress, tea steam'),
      nichePrompt('typewriter table scattered pages, round glasses pushed up, concentrated expression'),
      nichePrompt('forest path fallen leaves, wool coat and knee boots, book under arm'),
      nichePrompt('art studio easel corner, paint-stained smock over turtleneck, charcoal on fingers'),
      nichePrompt('vintage train compartment reading poetry, beret and trench coat'),
      nichePrompt('cathedral steps sketching architecture, long braid over shoulder'),
      nichePrompt('bookshop ladder reaching top shelf, corduroy pants and loafers'),
      nichePrompt('midnight desk lamp only light, oversized sweater, annotated classics open'),
    ],
  },
  {
    id: 'y2k',
    label: 'Y2K',
    description: 'Low-rise, butterfly clips, frosted makeup, flip-phone era pop princess.',
    defaultHairLock: 'crimped hair with butterfly clips and frosted highlights',
    prompts: [
      nichePrompt('bedroom poster wall low-rise jeans and baby tee, butterfly clips, flip phone in hand'),
      nichePrompt('mall food court table soda and fries, velour tracksuit, chunky platforms'),
      nichePrompt('car passenger seat CD player era, mini skirt and tinted sunglasses'),
      nichePrompt('bathroom frosted lip gloss application, rhinestone belly chain visible'),
      nichePrompt('arcade photo booth strip holding prints, pigtails and frosted eyeshadow'),
      nichePrompt('pool party inflatable ring, metallic bikini and visor'),
      nichePrompt('dance routine living room, baggy cargo pants low on hips, crop tank'),
      nichePrompt('bedazzled flip phone mirror selfie, pink velour set, rhinestone accessories'),
      nichePrompt('skate rink counter leaning, leg warmers and mini backpack'),
      nichePrompt('backseat limo party aesthetic, glitter top and feather boa'),
      nichePrompt('computer desk early 2000s nostalgia, chunky highlights, candy lip gloss'),
      nichePrompt('rooftop sunset denim mini skirt and halter top, frosted lip smile'),
    ],
  },
  {
    id: 'clean-girl',
    label: 'Clean Girl',
    description: 'Minimal glam, slick bun, gold hoops, dewy skin, expensive simple aesthetic.',
    defaultHairLock: 'slicked back low bun or clean middle-part straight hair',
    prompts: [
      nichePrompt('white bathroom slick bun and gold hoop earrings, dewy skin, white towel robe'),
      nichePrompt('minimal apartment neutral tones, beige co-ord set, holding green juice'),
      nichePrompt('elevator mirror outfit check, tailored blazer and straight-leg trousers'),
      nichePrompt('farmers market canvas tote, linen dress and simple sandals, fresh flowers'),
      nichePrompt('yoga studio exit glowing skin, matching neutral active set'),
      nichePrompt('coffee shop laptop work, oversized white shirt, delicate jewelry stack'),
      nichePrompt('bed white sheets skincare morning, satin pajama set, sunlight'),
      nichePrompt('city crosswalk structured bag and cat-eye sunglasses, monochrome cream outfit'),
      nichePrompt('spa robe waiting area, fresh face post-facial glow'),
      nichePrompt('kitchen avocado toast prep, hair in claw clip, minimal gold necklace'),
      nichePrompt('balcony pilates mat, soft neutral sports set, calm expression'),
      nichePrompt('evening candle minimal dining table, slip dress simple elegance'),
    ],
  },
  {
    id: 'cottagecore',
    label: 'Cottagecore',
    description: 'Meadows, floral dresses, baking bread, fairy tale countryside soft life.',
    defaultHairLock: 'long wavy auburn hair with wildflower clip or braid',
    prompts: [
      nichePrompt('wildflower meadow spinning in floral midi dress, wicker basket on arm'),
      nichePrompt('farmhouse kitchen kneading bread flour on apron, morning sun through curtains'),
      nichePrompt('garden path with chickens in background, linen dress and rubber boots'),
      nichePrompt('reading under oak tree picnic quilt, straw hat beside'),
      nichePrompt('picking berries in sun hat and puff sleeve blouse, wooden crate'),
      nichePrompt('stone cottage doorstep with tea tray, cozy knit cardigan'),
      nichePrompt('drying herbs hanging kitchen, simple peasant dress, soft smile'),
      nichePrompt('bridge over stream barefoot, rolled dress hem, dreamy expression'),
      nichePrompt('bicycle with front basket flowers, vintage dress fluttering'),
      nichePrompt('writing at wooden desk open window, candle and pressed flowers'),
      nichePrompt('baking pie lattice crust, cheeks dusted flour, rustic interior'),
      nichePrompt('sunset wheat field golden light, long braid over shoulder, pastoral peace'),
    ],
  },
  {
    id: 'streetwear-baddie',
    label: 'Streetwear Baddie',
    description: 'Oversized hoodies, Jordans, city nights, confident urban flex.',
    defaultHairLock: 'long lace-front straight hair with middle part',
    prompts: [
      nichePrompt('parking garage oversized hoodie and biker shorts, Jordan sneakers on car hood'),
      nichePrompt('bodega entrance iced coffee, designer street fit and gold chains'),
      nichePrompt('subway platform waiting, puffer jacket and cargo pants, headphones on'),
      nichePrompt('rooftop night city lights, cropped puffer and baggy jeans, confident stance'),
      nichePrompt('sneaker store unboxing new pair, athleisure set and long acrylic nails'),
      nichePrompt('street mural background hands in pockets, graphic tee under open jacket'),
      nichePrompt('late night diner booth, tracksuit and iced chain, unbothered expression'),
      nichePrompt('crosswalk wide-leg pants and tiny top, designer bag, stride toward camera'),
      nichePrompt('car backseat fit check mirror, rim light on face'),
      nichePrompt('basketball court sidelines sitting on ball, oversized jersey dress'),
      nichePrompt('liquor store neon glow fur trim hood, city grit glamour'),
      nichePrompt('apartment floor sneaker wall collection behind, lounge set'),
    ],
  },
  {
    id: 'office-siren',
    label: 'Office Siren',
    description: 'Corporate glam, pencil skirts, glasses, power meetings, after-hours martini.',
    defaultHairLock: 'dark hair sleek low bun with face-framing layers',
    prompts: [
      nichePrompt('glass office conference room pencil skirt and silk blouse, reading glasses, pen poised'),
      nichePrompt('elevator full-length mirror adjusting blazer, stiletto heel crossed'),
      nichePrompt('desk late night laptop glow, blouse slightly open, tired seductive focus'),
      nichePrompt('coffee run crossbody bag and trench coat, takeaway cup, city morning'),
      nichePrompt('copy room leaning copier, fitted dress and ID lanyard, knowing glance'),
      nichePrompt('rooftop bar after work martini, blazer over shoulders'),
      nichePrompt('cab backseat reviewing phone emails, skirt slit, window streak lights'),
      nichePrompt('hallway power walk folders in hand, sharp eyeliner and pumps'),
      nichePrompt('window office skyline hands on hips, authoritative silhouette'),
      nichePrompt('break room espresso machine steam, rolled sleeves professional'),
      nichePrompt('parking structure unlocking car, commuter chic outfit'),
      nichePrompt('hotel business trip room desk, room service and laptop'),
    ],
  },
  {
    id: 'festival-girl',
    label: 'Festival Girl',
    description: 'Coachella energy, glitter, fringe, cowboy boots, desert sunset rave.',
    defaultHairLock: 'loose beach waves with glitter roots and braids',
    prompts: [
      nichePrompt('desert festival ferris wheel background fringe top and cutoffs, glitter on cheekbones'),
      nichePrompt('flower crown and mesh cover-up bikini, dusty boots, sunset field'),
      nichePrompt('body glitter application tent mirror, rhinestone bra top'),
      nichePrompt('dancing crowd blurred behind, arms up, neon face paint'),
      nichePrompt('camp site hammock between vans, bohemian layered outfit'),
      nichePrompt('main stage golden hour silhouette, flowing kimono and boots'),
      nichePrompt('face gems and braided hair, holding festival wristbands fan'),
      nichePrompt('ice cream truck line playful pose, crochet top and maxi skirt'),
      nichePrompt('LED poi glow night portrait, reflective jacket open'),
      nichePrompt('vintage van door sitting, fringe jacket and round sunglasses'),
      nichePrompt('temporary tattoo station artistic ink visible on shoulder'),
      nichePrompt('sunrise field tired happy smile, oversized festival tee as dress'),
    ],
  },
  {
    id: 'punk-rock',
    label: 'Punk Rock',
    description: 'Studs, patches, mosh pit, ripped fishnets, raw rebellious energy.',
    defaultHairLock: 'short choppy mohawk-inspired cut dyed crimson',
    prompts: [
      nichePrompt('venue alley brick wall band tee ripped, studded belt and combat boots'),
      nichePrompt('mosh pit edge crowd blur, screaming expression joyful rage'),
      nichePrompt('DIY jacket covered patches, smudged eyeliner, cigarette unlit prop'),
      nichePrompt('record shop flipping vinyl, plaid pants and chain wallet'),
      nichePrompt('basement show red light, fishnet tights under torn skirt'),
      nichePrompt('tattoo parlor waiting flash sheet on wall, punk crimson haircut'),
      nichePrompt('skate park ramp top edge sitting, band merch hoodie'),
      nichePrompt('street march energy combat boots stomping, layered punk fit'),
      nichePrompt('bar bathroom graffiti mirror, safety pin earring and dark lipstick'),
      nichePrompt('van tour bunk sleeping bag, exhausted post-show realness'),
      nichePrompt('guitar case open busking street corner, beanie and layers'),
      nichePrompt('rain alley neon sign reflection wet leather jacket'),
    ],
  },
  {
    id: 'ballerina-soft',
    label: 'Ballerina Soft',
    description: 'Studio mirrors, tights, elegance, soft discipline, pale aesthetic.',
    defaultHairLock: 'tight classical ballet bun with wispy flyaways',
    prompts: [
      nichePrompt('ballet barre stretching in leotard and pink tights, pointed foot on barre'),
      nichePrompt('studio mirror adjusting strap, wrap skirt and ballet shoes ribbon tied'),
      nichePrompt('center floor arabesque practice, sweat glow graceful concentration'),
      nichePrompt('window light sitting tying pointe shoes, leg warmers around ankles'),
      nichePrompt('backstage makeup mirror stage prep, tutu on rack behind'),
      nichePrompt('rooftop unexpected ballet pose urban contrast, soft chiffon skirt'),
      nichePrompt('piano corner contemporary flow, bare feet on wood floor'),
      nichePrompt('staircase elegant descent hand on rail, fitted black leotard'),
      nichePrompt('hydration break water bottle studio, hair in perfect bun'),
      nichePrompt('sunbeam floor split stretch, peaceful closed eyes'),
      nichePrompt('curtain peek before performance, costume bodice and stage focus'),
      nichePrompt('cool-down foam roller studio corner, oversized knit over leotard'),
    ],
  },
  {
    id: 'cowboy-country',
    label: 'Cowboy Country',
    description: 'Boots, hat, barn golden hour, pickup truck, Southern glam.',
    defaultHairLock: 'long sun-kissed blonde waves under cowboy hat',
    prompts: [
      nichePrompt('hay bale sitting cowboy hat and boots, denim shorts and plaid tied shirt'),
      nichePrompt('pickup truck tailgate sunset legs dangling, country concert tee'),
      nichePrompt('horse stable brushing mane, riding boots and jeans, barn dust light'),
      nichePrompt('line dancing bar neon beer sign, fringe jacket and belt buckle'),
      nichePrompt('open field wildflowers cowboy boot step forward, maxi dress wind'),
      nichePrompt('porch swing sweet tea glass, gingham top and cutoffs'),
      nichePrompt('bonfire night flannel tied waist bikini top underneath, warm glow'),
      nichePrompt('feed store aisle cowboy hat try-on mirror, denim on denim'),
      nichePrompt('dirt road walking guitar case optional, golden hour backlit'),
      nichePrompt('rodeo stands bleachers hat tilt shadow on eyes, confident country stare'),
      nichePrompt('kitchen country breakfast pancakes, messy morning hair under hat'),
      nichePrompt('fence rail lean overlooking pasture, boots crossed at ankle'),
    ],
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    description: 'Neon rain, futuristic streetwear, chrome, dystopian city nights.',
    defaultHairLock: 'wet-look asymmetric cut with neon blue tips',
    prompts: [
      nichePrompt('neon alley rain reflective puddle, holographic jacket and tech visor up'),
      nichePrompt('rooftop city megastructure background, LED face paint lines'),
      nichePrompt('underground club laser fog, chrome top and cargo tech pants'),
      nichePrompt('food stall night market neon signs, cybernetic aesthetic arm band'),
      nichePrompt('motorcycle futuristic lean chrome helmet under arm'),
      nichePrompt('apartment window cityscape rain streak, glow on face from screens'),
      nichePrompt('augmented reality glasses reflection, tight bodysuit utility straps'),
      nichePrompt('elevator metallic interior harsh light, sharp geometric haircut'),
      nichePrompt('bridge over highway light trails long exposure mood portrait'),
      nichePrompt('hacker desk multiple monitors glow on skin, wired headphones'),
      nichePrompt('street vendor noodle steam neon pink sign backdrop'),
      nichePrompt('parking lot drone lights overhead, tactical fashion stance'),
    ],
  },
  {
    id: 'mob-wife',
    label: 'Mob Wife',
    description: 'Fur coats, red lipstick, Italian luxury, power couple energy, bold gold.',
    defaultHairLock: 'big voluminous blowout dark hair, retro glam volume',
    prompts: [
      nichePrompt('restaurant booth red leather fur coat over black dress, wine glass stem'),
      nichePrompt('marble staircase descending gold jewelry stacked, dramatic eyeliner'),
      nichePrompt('convertible passenger seat headscarf and oversized sunglasses'),
      nichePrompt('kitchen espresso moka pot luxury apartment, silk robe and heels indoors'),
      nichePrompt('casino slot machine fur wrap slipping shoulder, bold red lip'),
      nichePrompt('shopping bags boutique street strut, maxi coat and stilettos'),
      nichePrompt('balcony cigarette unlit prop city night, champagne on railing'),
      nichePrompt('church steps unexpected fashion shot wide-brim hat veil up'),
      nichePrompt('garage luxury car keys in hand, leather gloves and pencil skirt'),
      nichePrompt('holiday table hosting pasta spread, apron over glam outfit'),
      nichePrompt('hotel hallway walking away look back, animal print dress'),
      nichePrompt('portrait close-up gold hoops and red nails hand near face'),
    ],
  },
  {
    id: 'tennis-preppy',
    label: 'Tennis Preppy',
    description: 'Country club whites, visor, old money sport, preppy energy.',
    defaultHairLock: 'preppy headband with straight polished ponytail',
    prompts: [
      nichePrompt('tennis court baseline white pleated skirt and polo, racket on shoulder'),
      nichePrompt('clubhouse lemonade patio visor and sweater over shoulders'),
      nichePrompt('locker room bench pre-match tying shoelace, athletic skirt set'),
      nichePrompt('golf cart passenger country club path, pastel outfit and pearls'),
      nichePrompt('spectator bleachers sunglasses and collared dress, scorecard in hand'),
      nichePrompt('pro shop trying visor mirror, crisp white sneakers'),
      nichePrompt('pool club cabana white bikini cover-up polo, iced tea'),
      nichePrompt('library campus ivy league aesthetic cardigan and tennis skirt'),
      nichePrompt('courtside water break towel over neck, sun flush cheeks'),
      nichePrompt('family estate driveway preppy crossover outfit crisp whites'),
      nichePrompt('sailboat deck unexpected preppy nautical whites'),
      nichePrompt('brunch terrace avocado toast preppy set pearl studs'),
    ],
  },
  {
    id: 'ski-luxe',
    label: 'Ski Luxe',
    description: 'Après-ski, fur boots, mountain lodge, hot cocoa, luxury winter sport.',
    defaultHairLock: 'loose waves peeking from beanie, aprés-ski glow',
    prompts: [
      nichePrompt('ski lodge fireplace fur vest over turtleneck, hot cocoa mug both hands'),
      nichePrompt('gondola cabin mountain view window, goggles on forehead puffer jacket'),
      nichePrompt('snow slope sunglasses reflection adjusting scarf, fitted ski suit'),
      nichePrompt('outdoor jacuzzi steam snow around shoulders, bikini top contrast'),
      nichePrompt('equipment rental shop trying boots, oversized puffer and leggings'),
      nichePrompt('mountain restaurant fondue table rosy cheeks from cold'),
      nichePrompt('snow angel laughing on back, winter gear partially unzipped'),
      nichePrompt('chalet balcony alpine peaks behind, coffee and blanket wrap'),
      nichePrompt('ski lift chair feet dangling sunset pink sky on snow'),
      nichePrompt('luxury boutique fur hat try-on mirror, designer ski aesthetic'),
      nichePrompt('ice bar carved walls fur coat cocktail, frozen glamour'),
      nichePrompt('cab ride window frost patterns face half lit village streetlights'),
    ],
  },
  {
    id: 'tattoo-model',
    label: 'Tattoo Model',
    description: 'Ink as identity, studio shoots, alternative glam, body art focus.',
    defaultHairLock: 'shaved side long top dyed platinum blonde',
    prompts: [
      nichePrompt('tattoo chair mid-session ink on forearm visible, artist hands out of frame'),
      nichePrompt('mirror showing back piece large tattoo, minimal black lingerie'),
      nichePrompt('street style ink sleeves rolled tee, coffee in hand'),
      nichePrompt('studio flash bare shoulder new tattoo wrap film shiny'),
      nichePrompt('pool edge bikini showing hip tattoo sunset'),
      nichePrompt('gym mirror athletic set between rib tattoos visible'),
      nichePrompt('art gallery opening little black dress neck tattoo visible'),
      nichePrompt('motorcycle straddle seat leather jacket open on chest ink'),
      nichePrompt('bedroom morning sheets shoulder blade tattoo morning light'),
      nichePrompt('skull reference flash wall choosing design pointing'),
      nichePrompt('beach walk sarong hip and thigh tattoos wind'),
      nichePrompt('close-up fresh hand tattoos rings stacked portrait'),
    ],
  },
  {
    id: 'vampire-romantic',
    label: 'Vampire Romantic',
    description: 'Pale dramatic, blood-red accents, gothic romance crossover, moonlit.',
    defaultHairLock: 'waist-length black hair with blood-red ombré ends',
    prompts: [
      nichePrompt('moonlit balcony pale skin dark dress red lipstick stark, choker with gem'),
      nichePrompt('candle cathedral aisle long coat trailing, ethereal walk'),
      nichePrompt('rose garden at night holding deep red rose, melancholic beauty'),
      nichePrompt('velvet coffin aesthetic photoshoot decorative, lace dress'),
      nichePrompt('rain window streak tracing finger on glass, reflection mood'),
      nichePrompt('grand staircase blood-red gown train flowing, overhead chandelier dim'),
      nichePrompt('forest fog white dress unexpected bride-of-darkness vibe'),
      nichePrompt('antique mirror artistic gothic portrait pose'),
      nichePrompt('chalice goblet red drink prop elegant table gothic manor'),
      nichePrompt('balcony cape fabric spread artistic silhouette'),
      nichePrompt('library ancient tome candle reading pale illuminated from below'),
      nichePrompt('graveyard iron gate hand on bars longing expression romantic horror'),
    ],
  },
  {
    id: 'gamer-girl',
    label: 'Gamer Girl',
    description: 'Cozy stream setup, pastel peripherals, hoodies, playful competitive vibe.',
    defaultHairLock: 'pastel pink headset hair, space buns optional',
    prompts: [
      nichePrompt('streaming desk dual monitors RGB pastel, hoodie and shorts wave to chat'),
      nichePrompt('bean bag floor handheld console playing, oversized tee and socks'),
      nichePrompt('gaming cafe booth headphones around neck, bubble tea beside keyboard'),
      nichePrompt('bed propped pillows laptop on lap victory smile screen glow'),
      nichePrompt('collectible shelf figurines background fit check mirror cute pose'),
      nichePrompt('LAN party tournament badge lanyard focused expression headset mic'),
      nichePrompt('kitchen break instant noodles gaming break hair messy bun'),
      nichePrompt('co-op couch second controller offered toward camera inviting play'),
      nichePrompt('ring light close-up wink thumbnail face shot streamer aesthetic'),
      nichePrompt('VR headset lifted on forehead amazed expression living room'),
      nichePrompt('discord voice late night snacks chips bag dark room monitor glow'),
      nichePrompt('packaging unboxing new keyboard pastel keycaps excited face'),
    ],
  },
  {
    id: 'latina-glam',
    label: 'Latina Glam',
    description: 'Bold glam makeup, gold jewelry, confident curves-forward lifestyle brand.',
    defaultHairLock: 'thick voluminous dark curls with golden highlights',
    prompts: [
      nichePrompt('night city rooftop gold hoop earrings and bodycon dress, confident hip tilt'),
      nichePrompt('kitchen making cafecito cinnamon stick, silk robe and gold bracelets'),
      nichePrompt('beach sunset sarong and bikini gold chain belt wind in curls'),
      nichePrompt('car selfie driver seat sunglasses pushed up bold lip gloss smile'),
      nichePrompt('family party dancing kitchen blurred relatives background festive joy'),
      nichePrompt('salon fresh blowout mirror gold highlights in dark curls proud smile'),
      nichePrompt('pool party inflatable gold jewelry layered wet skin glow'),
      nichePrompt('street mural colorful background matching vibrant outfit energy'),
      nichePrompt('balcony morning coffee city view oversized shirt legs on rail'),
      nichePrompt('nightclub bathroom glam touch-up red lip liner sharp'),
      nichePrompt('farmers market fruit stand choosing mango bright dress'),
      nichePrompt('yacht rail ocean wind hair flying gold body chain bikini cover'),
    ],
  },
  {
    id: 'maid-aesthetic',
    label: 'Maid Aesthetic',
    description: 'Frills, lace apron, playful service fantasy, polished domestic glam.',
    defaultHairLock: 'short bob with headband and ribbon detail',
    prompts: [
      nichePrompt('luxury apartment feather duster playful pose frilled uniform and thigh highs'),
      nichePrompt('kitchen counter serving tray cookies lace headpiece smile'),
      nichePrompt('bedroom making sheets corner hospital fold precise playful glance'),
      nichePrompt('hallway curtsy greeting pose classic maid dress white apron'),
      nichePrompt('tea set pouring cup lace gloves delicate concentration'),
      nichePrompt('bookshelf organizing ladder step stool uniform skirt flare'),
      nichePrompt('mirror adjusting headpiece ribbon chin down eyes up'),
      nichePrompt('window cleaning squeegee playful wink breaking fourth wall'),
      nichePrompt('lounge dusting piano frills and heels domestic fantasy'),
      nichePrompt('break room sitting with tea cup finally resting cute tired smile'),
      nichePrompt('grand staircase serving champagne tray formal maid variant'),
      nichePrompt('closet organizing outfits hanging cheeky expression'),
    ],
  },
  {
    id: 'nurse-playful',
    label: 'Nurse Playful',
    description: 'Playful medical fantasy aesthetic, scrubs or costume, cheerful care vibe.',
    defaultHairLock: 'hair in clip-up nurse-cap friendly style',
    prompts: [
      nichePrompt('bright clinic hallway clipboard and stethoscope prop friendly wink fitted scrubs'),
      nichePrompt('break room coffee laugh with coworkers blurred wholesome energy'),
      nichePrompt('supply cabinet organizing playful tongue out cute scrubs print'),
      nichePrompt('patient room window light compassionate soft smile costume aesthetic'),
      nichePrompt('hallway wheels desk chair rolling fun speed blur playful'),
      nichePrompt('mirror cap adjustment red cross detail ready for shift'),
      nichePrompt('outdoor hospital entrance end-shift jacket over scrubs sunset'),
      nichePrompt('study desk nursing textbook highlighter messy bun focus'),
      nichePrompt('elevator selfie scrubs and sneakers long shift tired cute'),
      nichePrompt('cafeteria salad lunch tray healthy nurse lifestyle'),
      nichePrompt('parking lot car door opening duffel bag gym and work crossover'),
      nichePrompt('ward teddy bear prop warm nurturing expression costume'),
    ],
  },
  {
    id: 'beach-bombshell',
    label: 'Beach Bombshell',
    description: 'Classic baywatch energy, golden tan, bikini confidence, ocean glam.',
    defaultHairLock: 'long honey-blonde beach waves, sun-lightened ends',
    prompts: [
      nichePrompt('shoreline walking bikini and sarong wet hair wind ocean spray'),
      nichePrompt('lifeguard tower sitting red one-piece sunglasses tan lines aesthetic'),
      nichePrompt('beach volleyball mid-jump athletic bikini sand flying'),
      nichePrompt('tiki bar pineapple drink tropical bikini gold body oil sheen'),
      nichePrompt('yacht ladder climbing out of water bikini dripping sun flare'),
      nichePrompt('hammock between palms book down looking at camera relaxed bombshell'),
      nichePrompt('convertible beach road hair flying bikini top and high waist shorts'),
      nichePrompt('sunset pier leaning rail silhouette curves ocean orange sky'),
      nichePrompt('pool inflatable flamingo riding playful splash'),
      nichePrompt('hotel balcony robe open bikini underneath coffee morning ocean view'),
      nichePrompt('underwater half above half below surface bubble escape artistic'),
      nichePrompt('beach photoshoot reflector out of frame professional bikini glam'),
    ],
  },
  {
    id: 'angel-soft',
    label: 'Angel Soft',
    description: 'Soft white, ethereal, feathered, halo-lit innocence with glam edge.',
    defaultHairLock: 'soft platinum waves with halo-lit glow',
    prompts: [
      nichePrompt('white silk sheets angel wings costume photoshoot soft smile halo ring light'),
      nichePrompt('cloud backdrop studio all white lingerie set feather boa delicate'),
      nichePrompt('church window stained light white dress hands in prayer profile'),
      nichePrompt('field white flowers spinning dress fabric floating ethereal'),
      nichePrompt('mirror white lace robe open gentle touch collarbone innocent gaze'),
      nichePrompt('balcony white chiffon night city soft glow behind angel silhouette'),
      nichePrompt('studio floor lying on white fur wings spread artistic editorial'),
      nichePrompt('bubble bath foam shoulders white petals floating candle ring'),
      nichePrompt('staircase heaven aesthetic all white outfit ascending look back'),
      nichePrompt('close-up dewy skin freckles soft lip gloss eyes upward dreamy'),
      nichePrompt('garden fountain white sundress water mist rainbow light'),
      nichePrompt('bedroom fairy lights white corset soft wings partial cosplay romantic'),
    ],
  },
]
