import { nichePrompt, type NicheDefinition } from '@/lib/niche-utils'

/** 43 additional branded niches (~12 prompts each). */
export const EXTRA_NICHE_DEFINITIONS: NicheDefinition[] = [
  {
    id: 'coquette',
    label: 'Coquette',
    description: 'Bows, ribbons, soft pink, romantic feminine, doe eyes, hyper-feminine brand.',
    defaultHairLock: 'long dark hair with bow accessories and soft romantic curls',
    prompts: [
      nichePrompt('in a pink bedroom wearing a white lace camisole and ribbon choker, holding a heart mirror, soft blush makeup and doe-eyed expression'),
      nichePrompt('on a velvet chair in a satin mini dress with bow straps, legs tucked sideways, playing with pearl necklace'),
      nichePrompt('at a bakery counter in a pink gingham dress, holding a macaron box, sweet shy smile'),
      nichePrompt('kneeling on bed in oversized pink cardigan falling off shoulders, lace shorts, writing love note'),
      nichePrompt('in bathroom applying lip gloss, lace robe, bow in hair, soft ring light'),
      nichePrompt('on picnic blanket in white sundress with pink ribbon belt, strawberries and diary nearby'),
      nichePrompt('leaning on piano in corset top and tulle skirt, romantic candle glow'),
      nichePrompt('mirror selfie in pink bathroom, heart pajama set, fluffy slippers'),
      nichePrompt('on balcony at dusk in slip dress and faux fur wrap, holding rose tea cup'),
      nichePrompt('curled on window seat reading romance novel, knee socks and oversized sweater'),
      nichePrompt('at vanity surrounded by ribbons and perfume, lace bralette visible under open blouse'),
      nichePrompt('walking cobblestone street in ballet flats and mini skirt, soft sun on face'),
    ],
  },
  {
    id: 'e-girl',
    label: 'E-Girl',
    description: 'Gaming aesthetic, streak hair, chokers, striped sleeves, LED room, playful energy.',
    defaultHairLock: 'two-tone hair black with bright pink front streaks, winged liner',
    prompts: [
      nichePrompt('at RGB gaming desk wearing striped long sleeve under black tee, choker and chain belt, headset on'),
      nichePrompt('bedroom mirror selfie with LED strips pink and purple, crop top and plaid skirt'),
      nichePrompt('on gaming chair legs up, oversized hoodie and thigh highs, energy drink on desk'),
      nichePrompt('close-up face heavy winged liner and heart stamp under eye, neon sign glow'),
      nichePrompt('streaming setup wave to camera, cat ear headset, playful wink'),
      nichePrompt('convenience store night run, mesh top under jacket, platform sneakers'),
      nichePrompt('lying on bed scrolling phone, fishnet sleeves and shorts, posters on wall'),
      nichePrompt('kitchen making instant ramen, oversized band tee, messy e-girl makeup'),
      nichePrompt('skateboard park sitting on board, striped arm warmers, chain necklace'),
      nichePrompt('bathroom colorful makeup spread, dye-streak hair in clip, playful expression'),
      nichePrompt('arcade claw machine reaching up, cargo pants and crop hoodie'),
      nichePrompt('rainy window gamer mood, blanket and laptop glow on face'),
    ],
  },
  {
    id: 'fitness-baddie',
    label: 'Fitness Baddie',
    description: 'Gym glam, matching sets, squats, protein shakes, athletic confidence.',
    defaultHairLock: 'high ponytail or slick braid, sporty sleek hair',
    prompts: [
      nichePrompt('gym mirror selfie in matching scrunch-butt leggings set, post-workout glow, water bottle in hand'),
      nichePrompt('mid squat rack with barbell, focused expression, hair in high ponytail'),
      nichePrompt('outdoor stair sprint in sports bra and biker shorts, morning sun'),
      nichePrompt('smoothie bar post-workout, tank top and joggers, confident smile'),
      nichePrompt('yoga mat stretch arch back, matching pastel set, studio windows'),
      nichePrompt('locker room bench tying sneaker, defined abs visible, gym bag open'),
      nichePrompt('residential gym cable machine pull, intense eye contact with camera'),
      nichePrompt('track field starting blocks pose, runner aesthetic, wind in ponytail'),
      nichePrompt('protein shake kitchen selfie, oversized gym hoodie open on sports set'),
      nichePrompt('boxing bag mid-punch, hand wraps, fierce athletic energy'),
      nichePrompt('poolside lounge after swim laps, athletic one-piece, wet hair slicked'),
      nichePrompt('sunset rooftop jump rope pause, city backdrop, sweat glow editorial'),
    ],
  },
  {
    id: 'dark-academia',
    label: 'Dark Academia',
    description: 'Tweed, libraries, autumn leaves, vintage glasses, moody scholarly romance.',
    defaultHairLock: 'dark brown hair in low messy bun or loose vintage waves',
    prompts: [
      nichePrompt('in old library aisle stacked books to ceiling, tweed blazer and turtleneck, reading leather volume'),
      nichePrompt('autumn campus bench with coffee and notebook, long coat and scarf, thoughtful gaze'),
      nichePrompt('candlelit desk writing letter, ink pen and wax seal, vest and white shirt'),
      nichePrompt('museum hall marble bust background, long dark skirt and oxford shoes'),
      nichePrompt('rain on Gothic university window, cardigan over slip dress, tea steam'),
      nichePrompt('typewriter table scattered pages, round glasses pushed up, concentrated expression'),
      nichePrompt('forest path fallen leaves, wool coat and knee boots, book under arm'),
      nichePrompt('art studio easel corner, paint-stained smock over turtleneck, charcoal on fingers'),
      nichePrompt('vintage train compartment reading poetry, beret and trench coat'),
      nichePrompt('cathedral steps sketching architecture, long braid over shoulder'),
      nichePrompt('bookshop ladder reaching top shelf, corduroy pants and loafers'),
      nichePrompt('midnight desk lamp only light, oversized sweater, annotated classics open'),
    ],
  },
  {
    id: 'y2k',
    label: 'Y2K',
    description: 'Low-rise, butterfly clips, frosted makeup, flip-phone era pop princess.',
    defaultHairLock: 'crimped hair with butterfly clips and frosted highlights',
    prompts: [
      nichePrompt('bedroom poster wall low-rise jeans and baby tee, butterfly clips, flip phone in hand'),
      nichePrompt('mall food court table soda and fries, velour tracksuit, chunky platforms'),
      nichePrompt('car passenger seat CD player era, mini skirt and tinted sunglasses'),
      nichePrompt('bathroom frosted lip gloss application, rhinestone belly chain visible'),
      nichePrompt('arcade photo booth strip holding prints, pigtails and frosted eyeshadow'),
      nichePrompt('pool party inflatable ring, metallic bikini and visor'),
      nichePrompt('dance routine living room, baggy cargo pants low on hips, crop tank'),
      nichePrompt('bedazzled flip phone mirror selfie, pink velour set, rhinestone accessories'),
      nichePrompt('skate rink counter leaning, leg warmers and mini backpack'),
      nichePrompt('backseat limo party aesthetic, glitter top and feather boa'),
      nichePrompt('computer desk early 2000s nostalgia, chunky highlights, candy lip gloss'),
      nichePrompt('rooftop sunset denim mini skirt and halter top, frosted lip smile'),
    ],
  },
  {
    id: 'clean-girl',
    label: 'Clean Girl',
    description: 'Minimal glam, slick bun, gold hoops, dewy skin, expensive simple aesthetic.',
    defaultHairLock: 'slicked back low bun or clean middle-part straight hair',
    prompts: [
      nichePrompt('white bathroom slick bun and gold hoop earrings, dewy skin, white towel robe'),
      nichePrompt('minimal apartment neutral tones, beige co-ord set, holding green juice'),
      nichePrompt('elevator mirror outfit check, tailored blazer and straight-leg trousers'),
      nichePrompt('farmers market canvas tote, linen dress and simple sandals, fresh flowers'),
      nichePrompt('yoga studio exit glowing skin, matching neutral active set'),
      nichePrompt('coffee shop laptop work, oversized white shirt, delicate jewelry stack'),
      nichePrompt('bed white sheets skincare morning, satin pajama set, sunlight'),
      nichePrompt('city crosswalk structured bag and cat-eye sunglasses, monochrome cream outfit'),
      nichePrompt('spa robe waiting area, fresh face post-facial glow'),
      nichePrompt('kitchen avocado toast prep, hair in claw clip, minimal gold necklace'),
      nichePrompt('balcony pilates mat, soft neutral sports set, calm expression'),
      nichePrompt('evening candle minimal dining table, slip dress simple elegance'),
    ],
  },
  {
    id: 'cottagecore',
    label: 'Cottagecore',
    description: 'Meadows, floral dresses, baking bread, fairy tale countryside soft life.',
    defaultHairLock: 'long wavy auburn hair with wildflower clip or braid',
    prompts: [
      nichePrompt('wildflower meadow spinning in floral midi dress, wicker basket on arm'),
      nichePrompt('farmhouse kitchen kneading bread flour on apron, morning sun through curtains'),
      nichePrompt('garden path with chickens in background, linen dress and rubber boots'),
      nichePrompt('reading under oak tree picnic quilt, straw hat beside'),
      nichePrompt('picking berries in sun hat and puff sleeve blouse, wooden crate'),
      nichePrompt('stone cottage doorstep with tea tray, cozy knit cardigan'),
      nichePrompt('drying herbs hanging kitchen, simple peasant dress, soft smile'),
      nichePrompt('bridge over stream barefoot, rolled dress hem, dreamy expression'),
      nichePrompt('bicycle with front basket flowers, vintage dress fluttering'),
      nichePrompt('writing at wooden desk open window, candle and pressed flowers'),
      nichePrompt('baking pie lattice crust, cheeks dusted flour, rustic interior'),
      nichePrompt('sunset wheat field golden light, long braid over shoulder, pastoral peace'),
    ],
  },
  {
    id: 'streetwear-baddie',
    label: 'Streetwear Baddie',
    description: 'Oversized hoodies, Jordans, city nights, confident urban flex.',
    defaultHairLock: 'long lace-front straight hair with middle part',
    prompts: [
      nichePrompt('parking garage oversized hoodie and biker shorts, Jordan sneakers on car hood'),
      nichePrompt('bodega entrance iced coffee, designer street fit and gold chains'),
      nichePrompt('subway platform waiting, puffer jacket and cargo pants, headphones on'),
      nichePrompt('rooftop night city lights, cropped puffer and baggy jeans, confident stance'),
      nichePrompt('sneaker store unboxing new pair, athleisure set and long acrylic nails'),
      nichePrompt('street mural background hands in pockets, graphic tee under open jacket'),
      nichePrompt('late night diner booth, tracksuit and iced chain, unbothered expression'),
      nichePrompt('crosswalk wide-leg pants and tiny top, designer bag, stride toward camera'),
      nichePrompt('car backseat fit check mirror, rim light on face'),
      nichePrompt('basketball court sidelines sitting on ball, oversized jersey dress'),
      nichePrompt('liquor store neon glow fur trim hood, city grit glamour'),
      nichePrompt('apartment floor sneaker wall collection behind, lounge set'),
    ],
  },
  {
    id: 'office-siren',
    label: 'Office Siren',
    description: 'Corporate glam, pencil skirts, glasses, power meetings, after-hours martini.',
    defaultHairLock: 'dark hair sleek low bun with face-framing layers',
    prompts: [
      nichePrompt('glass office conference room pencil skirt and silk blouse, reading glasses, pen poised'),
      nichePrompt('elevator full-length mirror adjusting blazer, stiletto heel crossed'),
      nichePrompt('desk late night laptop glow, blouse slightly open, tired seductive focus'),
      nichePrompt('coffee run crossbody bag and trench coat, takeaway cup, city morning'),
      nichePrompt('copy room leaning copier, fitted dress and ID lanyard, knowing glance'),
      nichePrompt('rooftop bar after work martini, blazer over shoulders'),
      nichePrompt('cab backseat reviewing phone emails, skirt slit, window streak lights'),
      nichePrompt('hallway power walk folders in hand, sharp eyeliner and pumps'),
      nichePrompt('window office skyline hands on hips, authoritative silhouette'),
      nichePrompt('break room espresso machine steam, rolled sleeves professional'),
      nichePrompt('parking structure unlocking car, commuter chic outfit'),
      nichePrompt('hotel business trip room desk, room service and laptop'),
    ],
  },
  {
    id: 'festival-girl',
    label: 'Festival Girl',
    description: 'Coachella energy, glitter, fringe, cowboy boots, desert sunset rave.',
    defaultHairLock: 'loose beach waves with glitter roots and braids',
    prompts: [
      nichePrompt('desert festival ferris wheel background fringe top and cutoffs, glitter on cheekbones'),
      nichePrompt('flower crown and mesh cover-up bikini, dusty boots, sunset field'),
      nichePrompt('body glitter application tent mirror, rhinestone bra top'),
      nichePrompt('dancing crowd blurred behind, arms up, neon face paint'),
      nichePrompt('camp site hammock between vans, bohemian layered outfit'),
      nichePrompt('main stage golden hour silhouette, flowing kimono and boots'),
      nichePrompt('face gems and braided hair, holding festival wristbands fan'),
      nichePrompt('ice cream truck line playful pose, crochet top and maxi skirt'),
      nichePrompt('LED poi glow night portrait, reflective jacket open'),
      nichePrompt('vintage van door sitting, fringe jacket and round sunglasses'),
      nichePrompt('temporary tattoo station artistic ink visible on shoulder'),
      nichePrompt('sunrise field tired happy smile, oversized festival tee as dress'),
    ],
  },
  {
    id: 'punk-rock',
    label: 'Punk Rock',
    description: 'Studs, patches, mosh pit, ripped fishnets, raw rebellious energy.',
    defaultHairLock: 'short choppy mohawk-inspired cut dyed crimson',
    prompts: [
      nichePrompt('venue alley brick wall band tee ripped, studded belt and combat boots'),
      nichePrompt('mosh pit edge crowd blur, screaming expression joyful rage'),
      nichePrompt('DIY jacket covered patches, smudged eyeliner, cigarette unlit prop'),
      nichePrompt('record shop flipping vinyl, plaid pants and chain wallet'),
      nichePrompt('basement show red light, fishnet tights under torn skirt'),
      nichePrompt('tattoo parlor waiting flash sheet on wall, punk crimson haircut'),
      nichePrompt('skate park ramp top edge sitting, band merch hoodie'),
      nichePrompt('street march energy combat boots stomping, layered punk fit'),
      nichePrompt('bar bathroom graffiti mirror, safety pin earring and dark lipstick'),
      nichePrompt('van tour bunk sleeping bag, exhausted post-show realness'),
      nichePrompt('guitar case open busking street corner, beanie and layers'),
      nichePrompt('rain alley neon sign reflection wet leather jacket'),
    ],
  },
  {
    id: 'ballerina-soft',
    label: 'Ballerina Soft',
    description: 'Studio mirrors, tights, elegance, soft discipline, pale aesthetic.',
    defaultHairLock: 'tight classical ballet bun with wispy flyaways',
    prompts: [
      nichePrompt('ballet barre stretching in leotard and pink tights, pointed foot on barre'),
      nichePrompt('studio mirror adjusting strap, wrap skirt and ballet shoes ribbon tied'),
      nichePrompt('center floor arabesque practice, sweat glow graceful concentration'),
      nichePrompt('window light sitting tying pointe shoes, leg warmers around ankles'),
      nichePrompt('backstage makeup mirror stage prep, tutu on rack behind'),
      nichePrompt('rooftop unexpected ballet pose urban contrast, soft chiffon skirt'),
      nichePrompt('piano corner contemporary flow, bare feet on wood floor'),
      nichePrompt('staircase elegant descent hand on rail, fitted black leotard'),
      nichePrompt('hydration break water bottle studio, hair in perfect bun'),
      nichePrompt('sunbeam floor split stretch, peaceful closed eyes'),
      nichePrompt('curtain peek before performance, costume bodice and stage focus'),
      nichePrompt('cool-down foam roller studio corner, oversized knit over leotard'),
    ],
  },
  {
    id: 'cowboy-country',
    label: 'Cowboy Country',
    description: 'Boots, hat, barn golden hour, pickup truck, Southern glam.',
    defaultHairLock: 'long sun-kissed blonde waves under cowboy hat',
    prompts: [
      nichePrompt('hay bale sitting cowboy hat and boots, denim shorts and plaid tied shirt'),
      nichePrompt('pickup truck tailgate sunset legs dangling, country concert tee'),
      nichePrompt('horse stable brushing mane, riding boots and jeans, barn dust light'),
      nichePrompt('line dancing bar neon beer sign, fringe jacket and belt buckle'),
      nichePrompt('open field wildflowers cowboy boot step forward, maxi dress wind'),
      nichePrompt('porch swing sweet tea glass, gingham top and cutoffs'),
      nichePrompt('bonfire night flannel tied waist bikini top underneath, warm glow'),
      nichePrompt('feed store aisle cowboy hat try-on mirror, denim on denim'),
      nichePrompt('dirt road walking guitar case optional, golden hour backlit'),
      nichePrompt('rodeo stands bleachers hat tilt shadow on eyes, confident country stare'),
      nichePrompt('kitchen country breakfast pancakes, messy morning hair under hat'),
      nichePrompt('fence rail lean overlooking pasture, boots crossed at ankle'),
    ],
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    description: 'Neon rain, futuristic streetwear, chrome, dystopian city nights.',
    defaultHairLock: 'wet-look asymmetric cut with neon blue tips',
    prompts: [
      nichePrompt('neon alley rain reflective puddle, holographic jacket and tech visor up'),
      nichePrompt('rooftop city megastructure background, LED face paint lines'),
      nichePrompt('underground club laser fog, chrome top and cargo tech pants'),
      nichePrompt('food stall night market neon signs, cybernetic aesthetic arm band'),
      nichePrompt('motorcycle futuristic lean chrome helmet under arm'),
      nichePrompt('apartment window cityscape rain streak, glow on face from screens'),
      nichePrompt('augmented reality glasses reflection, tight bodysuit utility straps'),
      nichePrompt('elevator metallic interior harsh light, sharp geometric haircut'),
      nichePrompt('bridge over highway light trails long exposure mood portrait'),
      nichePrompt('hacker desk multiple monitors glow on skin, wired headphones'),
      nichePrompt('street vendor noodle steam neon pink sign backdrop'),
      nichePrompt('parking lot drone lights overhead, tactical fashion stance'),
    ],
  },
  {
    id: 'mob-wife',
    label: 'Mob Wife',
    description: 'Fur coats, red lipstick, Italian luxury, power couple energy, bold gold.',
    defaultHairLock: 'big voluminous blowout dark hair, retro glam volume',
    prompts: [
      nichePrompt('restaurant booth red leather fur coat over black dress, wine glass stem'),
      nichePrompt('marble staircase descending gold jewelry stacked, dramatic eyeliner'),
      nichePrompt('convertible passenger seat headscarf and oversized sunglasses'),
      nichePrompt('kitchen espresso moka pot luxury apartment, silk robe and heels indoors'),
      nichePrompt('casino slot machine fur wrap slipping shoulder, bold red lip'),
      nichePrompt('shopping bags boutique street strut, maxi coat and stilettos'),
      nichePrompt('balcony cigarette unlit prop city night, champagne on railing'),
      nichePrompt('church steps unexpected fashion shot wide-brim hat veil up'),
      nichePrompt('garage luxury car keys in hand, leather gloves and pencil skirt'),
      nichePrompt('holiday table hosting pasta spread, apron over glam outfit'),
      nichePrompt('hotel hallway walking away look back, animal print dress'),
      nichePrompt('portrait close-up gold hoops and red nails hand near face'),
    ],
  },
  {
    id: 'tennis-preppy',
    label: 'Tennis Preppy',
    description: 'Country club whites, visor, old money sport, preppy energy.',
    defaultHairLock: 'preppy headband with straight polished ponytail',
    prompts: [
      nichePrompt('tennis court baseline white pleated skirt and polo, racket on shoulder'),
      nichePrompt('clubhouse lemonade patio visor and sweater over shoulders'),
      nichePrompt('locker room bench pre-match tying shoelace, athletic skirt set'),
      nichePrompt('golf cart passenger country club path, pastel outfit and pearls'),
      nichePrompt('spectator bleachers sunglasses and collared dress, scorecard in hand'),
      nichePrompt('pro shop trying visor mirror, crisp white sneakers'),
      nichePrompt('pool club cabana white bikini cover-up polo, iced tea'),
      nichePrompt('library campus ivy league aesthetic cardigan and tennis skirt'),
      nichePrompt('courtside water break towel over neck, sun flush cheeks'),
      nichePrompt('family estate driveway preppy crossover outfit crisp whites'),
      nichePrompt('sailboat deck unexpected preppy nautical whites'),
      nichePrompt('brunch terrace avocado toast preppy set pearl studs'),
    ],
  },
  {
    id: 'ski-luxe',
    label: 'Ski Luxe',
    description: 'Après-ski, fur boots, mountain lodge, hot cocoa, luxury winter sport.',
    defaultHairLock: 'loose waves peeking from beanie, aprés-ski glow',
    prompts: [
      nichePrompt('ski lodge fireplace fur vest over turtleneck, hot cocoa mug both hands'),
      nichePrompt('gondola cabin mountain view window, goggles on forehead puffer jacket'),
      nichePrompt('snow slope sunglasses reflection adjusting scarf, fitted ski suit'),
      nichePrompt('outdoor jacuzzi steam snow around shoulders, bikini top contrast'),
      nichePrompt('equipment rental shop trying boots, oversized puffer and leggings'),
      nichePrompt('mountain restaurant fondue table rosy cheeks from cold'),
      nichePrompt('snow angel laughing on back, winter gear partially unzipped'),
      nichePrompt('chalet balcony alpine peaks behind, coffee and blanket wrap'),
      nichePrompt('ski lift chair feet dangling sunset pink sky on snow'),
      nichePrompt('luxury boutique fur hat try-on mirror, designer ski aesthetic'),
      nichePrompt('ice bar carved walls fur coat cocktail, frozen glamour'),
      nichePrompt('cab ride window frost patterns face half lit village streetlights'),
    ],
  },
  {
    id: 'tattoo-model',
    label: 'Tattoo Model',
    description: 'Ink as identity, studio shoots, alternative glam, body art focus.',
    defaultHairLock: 'shaved side long top dyed platinum blonde',
    prompts: [
      nichePrompt('tattoo chair mid-session ink on forearm visible, artist hands out of frame'),
      nichePrompt('mirror showing back piece large tattoo, minimal black lingerie'),
      nichePrompt('street style ink sleeves rolled tee, coffee in hand'),
      nichePrompt('studio flash bare shoulder new tattoo wrap film shiny'),
      nichePrompt('pool edge bikini showing hip tattoo sunset'),
      nichePrompt('gym mirror athletic set between rib tattoos visible'),
      nichePrompt('art gallery opening little black dress neck tattoo visible'),
      nichePrompt('motorcycle straddle seat leather jacket open on chest ink'),
      nichePrompt('bedroom morning sheets shoulder blade tattoo morning light'),
      nichePrompt('skull reference flash wall choosing design pointing'),
      nichePrompt('beach walk sarong hip and thigh tattoos wind'),
      nichePrompt('close-up fresh hand tattoos rings stacked portrait'),
    ],
  },
  {
    id: 'vampire-romantic',
    label: 'Vampire Romantic',
    description: 'Pale dramatic, blood-red accents, gothic romance crossover, moonlit.',
    defaultHairLock: 'waist-length black hair with blood-red ombré ends',
    prompts: [
      nichePrompt('moonlit balcony pale skin dark dress red lipstick stark, choker with gem'),
      nichePrompt('candle cathedral aisle long coat trailing, ethereal walk'),
      nichePrompt('rose garden at night holding deep red rose, melancholic beauty'),
      nichePrompt('velvet coffin aesthetic photoshoot decorative, lace dress'),
      nichePrompt('rain window streak tracing finger on glass, reflection mood'),
      nichePrompt('grand staircase blood-red gown train flowing, overhead chandelier dim'),
      nichePrompt('forest fog white dress unexpected bride-of-darkness vibe'),
      nichePrompt('antique mirror artistic gothic portrait pose'),
      nichePrompt('chalice goblet red drink prop elegant table gothic manor'),
      nichePrompt('balcony cape fabric spread artistic silhouette'),
      nichePrompt('library ancient tome candle reading pale illuminated from below'),
      nichePrompt('graveyard iron gate hand on bars longing expression romantic horror'),
    ],
  },
  {
    id: 'gamer-girl',
    label: 'Gamer Girl',
    description: 'Cozy stream setup, pastel peripherals, hoodies, playful competitive vibe.',
    defaultHairLock: 'pastel pink headset hair, space buns optional',
    prompts: [
      nichePrompt('streaming desk dual monitors RGB pastel, hoodie and shorts wave to chat'),
      nichePrompt('bean bag floor handheld console playing, oversized tee and socks'),
      nichePrompt('gaming cafe booth headphones around neck, bubble tea beside keyboard'),
      nichePrompt('bed propped pillows laptop on lap victory smile screen glow'),
      nichePrompt('collectible shelf figurines background fit check mirror cute pose'),
      nichePrompt('LAN party tournament badge lanyard focused expression headset mic'),
      nichePrompt('kitchen break instant noodles gaming break hair messy bun'),
      nichePrompt('co-op couch second controller offered toward camera inviting play'),
      nichePrompt('ring light close-up wink thumbnail face shot streamer aesthetic'),
      nichePrompt('VR headset lifted on forehead amazed expression living room'),
      nichePrompt('discord voice late night snacks chips bag dark room monitor glow'),
      nichePrompt('packaging unboxing new keyboard pastel keycaps excited face'),
    ],
  },
  {
    id: 'latina-glam',
    label: 'Latina Glam',
    description: 'Bold glam makeup, gold jewelry, confident curves-forward lifestyle brand.',
    defaultHairLock: 'thick voluminous dark curls with golden highlights',
    prompts: [
      nichePrompt('night city rooftop gold hoop earrings and bodycon dress, confident hip tilt'),
      nichePrompt('kitchen making cafecito cinnamon stick, silk robe and gold bracelets'),
      nichePrompt('beach sunset sarong and bikini gold chain belt wind in curls'),
      nichePrompt('car selfie driver seat sunglasses pushed up bold lip gloss smile'),
      nichePrompt('family party dancing kitchen blurred relatives background festive joy'),
      nichePrompt('salon fresh blowout mirror gold highlights in dark curls proud smile'),
      nichePrompt('pool party inflatable gold jewelry layered wet skin glow'),
      nichePrompt('street mural colorful background matching vibrant outfit energy'),
      nichePrompt('balcony morning coffee city view oversized shirt legs on rail'),
      nichePrompt('nightclub bathroom glam touch-up red lip liner sharp'),
      nichePrompt('farmers market fruit stand choosing mango bright dress'),
      nichePrompt('yacht rail ocean wind hair flying gold body chain bikini cover'),
    ],
  },
  {
    id: 'maid-aesthetic',
    label: 'Maid Aesthetic',
    description: 'Frills, lace apron, playful service fantasy, polished domestic glam.',
    defaultHairLock: 'short bob with headband and ribbon detail',
    prompts: [
      nichePrompt('luxury apartment feather duster playful pose frilled uniform and thigh highs'),
      nichePrompt('kitchen counter serving tray cookies lace headpiece smile'),
      nichePrompt('bedroom making sheets corner hospital fold precise playful glance'),
      nichePrompt('hallway curtsy greeting pose classic maid dress white apron'),
      nichePrompt('tea set pouring cup lace gloves delicate concentration'),
      nichePrompt('bookshelf organizing ladder step stool uniform skirt flare'),
      nichePrompt('mirror adjusting headpiece ribbon chin down eyes up'),
      nichePrompt('window cleaning squeegee playful wink breaking fourth wall'),
      nichePrompt('lounge dusting piano frills and heels domestic fantasy'),
      nichePrompt('break room sitting with tea cup finally resting cute tired smile'),
      nichePrompt('grand staircase serving champagne tray formal maid variant'),
      nichePrompt('closet organizing outfits hanging cheeky expression'),
    ],
  },
  {
    id: 'nurse-playful',
    label: 'Nurse Playful',
    description: 'Playful medical fantasy aesthetic, scrubs or costume, cheerful care vibe.',
    defaultHairLock: 'hair in clip-up nurse-cap friendly style',
    prompts: [
      nichePrompt('bright clinic hallway clipboard and stethoscope prop friendly wink fitted scrubs'),
      nichePrompt('break room coffee laugh with coworkers blurred wholesome energy'),
      nichePrompt('supply cabinet organizing playful tongue out cute scrubs print'),
      nichePrompt('patient room window light compassionate soft smile costume aesthetic'),
      nichePrompt('hallway wheels desk chair rolling fun speed blur playful'),
      nichePrompt('mirror cap adjustment red cross detail ready for shift'),
      nichePrompt('outdoor hospital entrance end-shift jacket over scrubs sunset'),
      nichePrompt('study desk nursing textbook highlighter messy bun focus'),
      nichePrompt('elevator selfie scrubs and sneakers long shift tired cute'),
      nichePrompt('cafeteria salad lunch tray healthy nurse lifestyle'),
      nichePrompt('parking lot car door opening duffel bag gym and work crossover'),
      nichePrompt('ward teddy bear prop warm nurturing expression costume'),
    ],
  },
  {
    id: 'beach-bombshell',
    label: 'Beach Bombshell',
    description: 'Classic baywatch energy, golden tan, bikini confidence, ocean glam.',
    defaultHairLock: 'long honey-blonde beach waves, sun-lightened ends',
    prompts: [
      nichePrompt('shoreline walking bikini and sarong wet hair wind ocean spray'),
      nichePrompt('lifeguard tower sitting red one-piece sunglasses tan lines aesthetic'),
      nichePrompt('beach volleyball mid-jump athletic bikini sand flying'),
      nichePrompt('tiki bar pineapple drink tropical bikini gold body oil sheen'),
      nichePrompt('yacht ladder climbing out of water bikini dripping sun flare'),
      nichePrompt('hammock between palms book down looking at camera relaxed bombshell'),
      nichePrompt('convertible beach road hair flying bikini top and high waist shorts'),
      nichePrompt('sunset pier leaning rail silhouette curves ocean orange sky'),
      nichePrompt('pool inflatable flamingo riding playful splash'),
      nichePrompt('hotel balcony robe open bikini underneath coffee morning ocean view'),
      nichePrompt('underwater half above half below surface bubble escape artistic'),
      nichePrompt('beach photoshoot reflector out of frame professional bikini glam'),
    ],
  },
  {
    id: 'angel-soft',
    label: 'Angel Soft',
    description: 'Soft white, ethereal, feathered, halo-lit innocence with glam edge.',
    defaultHairLock: 'soft platinum waves with halo-lit glow',
    prompts: [
      nichePrompt('white silk sheets angel wings costume photoshoot soft smile halo ring light'),
      nichePrompt('cloud backdrop studio all white lingerie set feather boa delicate'),
      nichePrompt('church window stained light white dress hands in prayer profile'),
      nichePrompt('field white flowers spinning dress fabric floating ethereal'),
      nichePrompt('mirror white lace robe open gentle touch collarbone innocent gaze'),
      nichePrompt('balcony white chiffon night city soft glow behind angel silhouette'),
      nichePrompt('studio floor lying on white fur wings spread artistic editorial'),
      nichePrompt('bubble bath foam shoulders white petals floating candle ring'),
      nichePrompt('staircase heaven aesthetic all white outfit ascending look back'),
      nichePrompt('close-up dewy skin freckles soft lip gloss eyes upward dreamy'),
      nichePrompt('garden fountain white sundress water mist rainbow light'),
      nichePrompt('bedroom fairy lights white corset soft wings partial cosplay romantic'),
    ],
  },
  {
    id: 'sorority-girl',
    label: 'Sorority Girl',
    description: 'Campus life, game day, dorm rooms, frat parties, Greek life confidence.',
    defaultHairLock: 'long straight hair with claw clip, campus-casual center part',
    prompts: [
      nichePrompt('dorm room fairy lights string, oversized crewneck and bike shorts, fuzzy socks, laptop and textbooks scattered'),
      nichePrompt('tailgate parking lot game day face paint, cropped jersey tied at waist, red solo cup prop'),
      nichePrompt('sorority house front steps solo photo pose, letters hoodie, sunglasses on head'),
      nichePrompt('library study room late night, hair in messy bun, oversized flannel over tank, highlighters spread'),
      nichePrompt('frat party basement red cup in hand, sequin mini dress, playful laugh mid-conversation'),
      nichePrompt('campus quad picnic blanket, backpack beside, iced coffee, casual sundress'),
      nichePrompt('dorm bathroom mirror pregame selfie, curling iron in hand, going-out outfit half done'),
      nichePrompt('football stadium bleachers cheering, oversized game day tee knotted, pom-poms'),
      nichePrompt('laundry room folding clothes, oversized university sweatshirt, hair in towel turban'),
      nichePrompt('rooftop party string lights, crop top and denim shorts, red cup in hand'),
      nichePrompt('morning walk to class tote bag and coffee, athleisure set, backpack straps'),
      nichePrompt('bunk bed dorm room lounging, pajama shorts and cropped tank, phone scrolling'),
    ],
  },
  {
    id: 'pinup-retro',
    label: 'Pin-Up Retro',
    description: '1950s Americana glamour, polka dots, victory rolls, classic diner and garage aesthetic.',
    defaultHairLock: 'victory rolls with red hair scarf, glossy vintage curls',
    prompts: [
      nichePrompt('diner booth vintage red vinyl seats, polka dot halter dress, milkshake with two straws'),
      nichePrompt('garage classic car hood sitting, red bandana in hair, high-waisted shorts and tied blouse'),
      nichePrompt('vintage kitchen apron over full-skirt dress, pie cooling on windowsill, cherry-red lipstick'),
      nichePrompt('photo booth curtain backdrop, off-shoulder gingham dress, playful wink'),
      nichePrompt('laundromat vintage machines, rolled-sleeve blouse and pencil skirt, hair in victory rolls'),
      nichePrompt('backyard clothesline vintage sundress, wicker basket, sun hat'),
      nichePrompt('record shop vintage jukebox, poodle skirt mid-twirl, saddle shoes'),
      nichePrompt('vintage boudoir mirror, satin slip and marabou robe, curling pin set half done'),
      nichePrompt('roadside motel neon sign glow, halter sundress, retro suitcase in hand'),
      nichePrompt('soda fountain counter stool, striped swimsuit under cardigan, cherry-topped ice cream'),
      nichePrompt('vintage bicycle basket of flowers, full skirt dress mid-twirl, gloved hands on handlebars'),
      nichePrompt('film noir alley lamp light, fitted pencil dress, red lips lit by streetlamp silhouette'),
    ],
  },
  {
    id: 'cosplay-con',
    label: 'Cosplay Con Girl',
    description: 'Convention floor energy, original fantasy costumes, colorful wigs, playful character embodiment.',
    defaultHairLock: 'long colorful wig straight with blunt bangs, convention-ready styling',
    prompts: [
      nichePrompt('convention hall banner backdrop blur, elf-ear fantasy armor costume, colorful wig, prop sword resting'),
      nichePrompt('artist alley table browsing prints, magical-girl costume with wand prop, pastel wig pigtails'),
      nichePrompt('hotel hallway con badge lanyard, warrior-princess costume with cape, dramatic eye makeup'),
      nichePrompt('photo op step-and-repeat wall, sci-fi bodysuit costume, holographic wig'),
      nichePrompt('green room touch-up mirror, half-finished cosplay makeup, wig cap visible'),
      nichePrompt('escalator convention crowd blur, fantasy corset costume, staff prop in hand'),
      nichePrompt('hotel room floor costume pieces laid out, fitting armor pauldron, focused expression'),
      nichePrompt('outdoor con meetup solo photo crop, fairy-wing costume, flower crown'),
      nichePrompt('vendor hall prop weapon browsing, cat-ear fantasy costume, playful pose'),
      nichePrompt('late night hotel room makeup half removed, natural face contrast candid'),
      nichePrompt('convention center stairs sitting rest, plush prop toy, tired happy smile'),
      nichePrompt('cosplay contest backstage nerves, elaborate gown costume, hands smoothing fabric'),
    ],
  },
  {
    id: 'biker-chick',
    label: 'Biker Chick',
    description: 'Chrome and leather road culture, open highway, garage grease, rebel confidence.',
    defaultHairLock: 'long tousled waves under a bandana, windswept from riding',
    prompts: [
      nichePrompt('open highway pulled over at vista, leather jacket over bikini top, motorcycle on kickstand'),
      nichePrompt('garage workbench wiping hands on rag, ripped denim and cropped tank, tools scattered'),
      nichePrompt('diner parking lot leaning on bike, aviators and leather vest, boots crossed'),
      nichePrompt('desert road dust cloud behind, riding chaps over shorts, helmet under arm'),
      nichePrompt('roadside gas station fill-up, fingerless gloves, bandana headband'),
      nichePrompt('biker rally crowd blur, leather corset vest, chain wallet swinging'),
      nichePrompt('garage neon beer sign wall, straddling bike seat, confident smirk'),
      nichePrompt('motel balcony overlooking bikes lined up, leather jacket open over tank, coffee in hand'),
      nichePrompt('back road sunset silhouette on bike, hair loose in wind, denim cutoffs'),
      nichePrompt('tattoo parlor waiting chair, riding jacket patches, boots up on bench'),
      nichePrompt('truck stop counter coffee, road-worn leather jacket, tired satisfied road-trip glow'),
      nichePrompt('scenic overlook photo op, arms crossed beside parked bike, mountains behind'),
    ],
  },
  {
    id: 'space-vixen',
    label: 'Space Vixen',
    description: 'Sci-fi futurism, metallic armor, alien landscapes, cinematic space-opera glamour.',
    defaultHairLock: 'sleek silver-white braid with metallic hair cuffs',
    prompts: [
      nichePrompt('spacecraft cockpit control panel glow, fitted metallic bodysuit, helmet resting on lap'),
      nichePrompt('alien desert twin suns backdrop, futuristic armor pieces, wind-swept hair'),
      nichePrompt('cargo bay corridor steam vents, tactical sci-fi jumpsuit, blaster prop holstered'),
      nichePrompt('observation deck starfield window, silver gown with structured shoulders, contemplative gaze'),
      nichePrompt('research lab hologram display, fitted lab suit, curious focused expression'),
      nichePrompt('docking bay ladder climbing, utility harness over bodysuit, confident stance'),
      nichePrompt('crashed pod wreckage scene, torn futuristic suit, determined survivor look'),
      nichePrompt('space bar neon alien lounge, metallic cocktail dress, holographic drink prop'),
      nichePrompt('zero-gravity chamber simulated float pose, sleek suit, hair fanned out'),
      nichePrompt('command bridge captain chair, structured uniform dress, authoritative posture'),
      nichePrompt('planet surface crystal cave glow, bioluminescent light on skin, ethereal suit'),
      nichePrompt('ship exterior airlock window view, helmet under arm, planet reflection in visor'),
    ],
  },
  {
    id: 'surfer-girl',
    label: 'Surfer Girl',
    description: 'Salt-water athletic beach culture, wetsuits and boards, sun-bleached golden-hour energy.',
    defaultHairLock: 'salt-tousled beach waves sun-bleached at the ends',
    prompts: [
      nichePrompt('dawn patrol beach walk board under arm, wetsuit peeled to waist, sunrise glow'),
      nichePrompt('paddling out lineup sitting on board, rashguard and bikini, ocean spray'),
      nichePrompt('board waxing on sand session prep, focused ritual, wetsuit unzipped'),
      nichePrompt('truck bed tailgate boards stacked, damp hair and towel wrap, post-surf tired smile'),
      nichePrompt('beach shower rinsing off sand, wetsuit half peeled, salt-crusted hair'),
      nichePrompt('rocky point break scouting waves, binoculars prop, windbreaker over swimsuit'),
      nichePrompt('van life surf trip door open, wetsuit drying on rack, coffee in hand'),
      nichePrompt('tide pool exploring barefoot, boardshorts and bikini top, curious crouch'),
      nichePrompt('longboard walking shoreline carried under arm, sun-kissed skin, confident stride'),
      nichePrompt('campfire beach night post-surf, hoodie over damp swimsuit, marshmallow stick'),
      nichePrompt('surf shop wax and fins browsing, boardshorts and rashguard, easy grin'),
      nichePrompt('cliff lookout scanning the swell, wetsuit top tied at waist, ocean wind in hair'),
    ],
  },
  {
    id: 'fairycore',
    label: 'Fairycore',
    description: 'Whimsical forest magic, gossamer wings, moss and moonlight, ethereal woodland fantasy.',
    defaultHairLock: 'loose braided crown with tiny flowers woven through',
    prompts: [
      nichePrompt('moss-covered forest clearing, sheer gossamer dress, delicate wing accessory'),
      nichePrompt('mushroom ring in moonlight, flower crown and bare feet, dreamy soft focus'),
      nichePrompt('hollow tree trunk doorway, layered petal-toned skirts, curious peeking pose'),
      nichePrompt('creek stones stepping barefoot, translucent wings catching light, playful balance'),
      nichePrompt('firefly meadow at dusk, flowing chiffon dress, hands cupped as if catching light'),
      nichePrompt('ivy-covered ruins pillars, vine-wrapped bodice, wistful gaze upward'),
      nichePrompt('toadstool cluster sitting cross-legged, leaf-textured dress, tiny woodland creature prop'),
      nichePrompt('misty pond lily pads, sheer draped fabric, reflection in still water'),
      nichePrompt('moonlit clearing mid-spin, iridescent wings spread, hair lifted mid-turn'),
      nichePrompt('ancient oak roots curled up resting, moss and lichen textured dress, peaceful sleep'),
      nichePrompt('wildflower field golden hour, flower crown, gossamer sleeves fluttering'),
      nichePrompt('crystal cave soft glow, ethereal gown, wonder-struck expression'),
    ],
  },
  {
    id: 'military-tactical',
    label: 'Military Tactical Baddie',
    description: 'Camo and combat-boot confidence, base life, tactical gear with feminine edge.',
    defaultHairLock: 'tight slicked bun with camo bandana',
    prompts: [
      nichePrompt('obstacle course pause wiping brow, camo tank and cargo pants, combat boots'),
      nichePrompt('base barracks bunk making bed corners sharp, fitted tee and dog tags'),
      nichePrompt('firing range stance focused, tactical vest over tank top, ear protection around neck'),
      nichePrompt('humvee hood leaning, camo cap and aviators, confident arms crossed'),
      nichePrompt('base gym fitness center pull-up bar, athletic tank and camo leggings'),
      nichePrompt('mess hall tray lunch break, fatigues jacket tied at waist, easy smile'),
      nichePrompt('helicopter pad wind whipping hair, flight suit unzipped over tank, dog tags swinging'),
      nichePrompt('night vision goggles pushed up on forehead, tactical gear, determined stare'),
      nichePrompt('rope climb training wall, camo sports bra and cargo shorts, chalk on hands'),
      nichePrompt('barracks locker organizing gear, dog tags and fitted tee, focused routine'),
      nichePrompt('desert camo backdrop convoy trucks, tactical vest, squinting into sun'),
      nichePrompt('off-duty base housing porch, camo shorts and tank, cold drink relaxing'),
    ],
  },
  {
    id: 'bridal-boudoir',
    label: 'Bridal Boudoir',
    description: 'Wedding-week intimacy, lace veils, bachelorette glam, romantic just-for-him energy.',
    defaultHairLock: 'soft bridal updo with loose face-framing tendrils',
    prompts: [
      nichePrompt('hotel suite morning-of, silk robe with bride lettering, veil draped over chair back'),
      nichePrompt('vanity mirror final touches, lace bodysuit under open robe, garter visible'),
      nichePrompt('window light veil as only accessory, white lace lingerie set, soft romantic gaze'),
      nichePrompt('bed scattered rose petals in heart shape, white lace teddy, veil pooled beside'),
      nichePrompt('floor-length mirror full silhouette, corset-style lingerie, veil clipped into half-up hair'),
      nichePrompt('champagne toast solo moment, silk robe open over lace set, bridal party dress on hanger behind'),
      nichePrompt('chaise lounge veil trailing to floor, white lace and satin ribbon details, soft smile'),
      nichePrompt('balcony morning light robe untied, garter and stockings, veil lifting slightly in breeze'),
      nichePrompt('vanity stool clasping necklace, lace bralette, wedding dress visible on mannequin behind'),
      nichePrompt('bed pillows propped reading vows card, silk slip, veil draped over headboard'),
      nichePrompt('bathroom mirror steam soft glow, towel and veil combination playful candid'),
      nichePrompt('suite doorway silhouette backlit, flowing lace robe, bouquet resting on side table'),
    ],
  },
  {
    id: 'trophy-wife',
    label: 'Trophy Wife',
    description: 'Polished suburban luxury, country-club mornings, gated-community glam, quiet-money confidence.',
    defaultHairLock: 'glossy blowout with face-framing layers, polished suburban glam',
    prompts: [
      nichePrompt('gated community driveway luxury SUV, athleisure set and oversized sunglasses, coffee tumbler'),
      nichePrompt('kitchen island marble morning routine, silk robe, fresh flower delivery box open'),
      nichePrompt('country club brunch patio, tailored linen dress, mimosa in hand'),
      nichePrompt('home gym mirror selfie, matching designer activewear, post-Pilates glow'),
      nichePrompt('backyard pool lounger, one-piece designer swimsuit, sun hat and cocktail'),
      nichePrompt('walk-in closet organizing designer bags, silk slip dress, morning light'),
      nichePrompt('school pickup line car window, oversized sunglasses, casual luxury loungewear'),
      nichePrompt('wine cellar tasting selection, fitted midi dress, glass swirling'),
      nichePrompt('home office video call blazer visible, pearl studs, laptop glow'),
      nichePrompt('garden party hosting neighbors, floral wrap dress, champagne tray'),
      nichePrompt('spa day robe on lounge chair, cucumber water, fresh manicure drying'),
      nichePrompt('primary suite vanity morning skincare, satin robe, orchid on counter'),
    ],
  },
  {
    id: 'golf-girl',
    label: 'Golf Girl',
    description: 'Country-club fairways, pleated skirts, visors, sunny course glamour.',
    defaultHairLock: 'sleek ponytail through a visor, polished sporty waves',
    prompts: [
      nichePrompt('on a driving range mid-golf-swing in a fitted golf polo and pleated skirt, weight shifted onto the lead leg with fabric swinging and a short hard shadow on the grass, sun visor and sunglasses, late-afternoon side light with specular on the forehead and club shaft, skin with visible pores and light sweat sheen, a few flyaway hairs under the visor, dusty club grip and scuffed range ball nearby, three-quarter body phone photo with mild wide-angle distortion and light grain, no beauty filter'),
      nichePrompt('seated on a clubhouse patio with a scorecard in hand, pastel golf polo, one gloved hand resting on a club leaning against the chair, warm porch light mixed with late sun, skin pores and slight freckling on the nose, a few loose hairs by the ear, condensation ring on the table and dusty club head, three-quarter candid phone framing with mild grain, no airbrush skin'),
      nichePrompt('riding a golf cart down the fairway, sleeveless top and visor, one hand on the wheel and the other on the seat back, wind lifting her ponytail, hard sun casting short shadows on the cart path, skin with visible pores and sun flush on cheeks, dusty dashboard and fingerprint on the wheel, three-quarter phone shot from beside the cart with mild wide-angle distortion and light grain'),
      nichePrompt('crouched on a putting green reading the line, golf skort and polo, elbows on knees, focused expression, soft overcast golf-course light with gentle ground shadow, skin pores and natural under-eye texture, a few flyaways under the visor, dew marks on the ball and scuffed putter face, low phone angle three-quarter body with light grain, no beauty filter'),
      nichePrompt('in a pro shop trying on a golf glove, argyle sweater vest over a polo, sunny window light across half her face, skin with visible pores and soft highlight on the cheekbone, a few loose hairs, clothing hangers and price tags softly blurred behind, phone selfie-style framing with mild wide-angle distortion and natural grain, candid not catalog'),
      nichePrompt('at the 19th hole bar with a celebratory drink, golf polo tied at the waist over a skort, leaning an elbow on the bar, warm interior tungsten mixed with window daylight, skin pores and slight shine on the nose, messy flyaways after a round, condensation on the glass and fingerprint smudge on the bar top, three-quarter candid phone photo with light grain'),
      nichePrompt('on the tee box at follow-through after a practice swing, pleated skirt flared mid-motion, weight on the front foot, wind in the ponytail through a visor, bright side sun with hard shadow on the tee box, skin pores and light sweat sheen, grass blades stuck to a golf shoe, three-quarter dynamic phone framing with mild motion in the skirt only and light grain, no beauty filter'),
      nichePrompt('standing in a sand trap for a bunker shot, visor shading her eyes, club raised behind her, stance dug into the sand with footprints, harsh overhead sun and bright sand bounce light, skin with visible pores and heat flush, dusty ankles and sand grains on the club face, three-quarter phone photo with mild wide-angle distortion and light grain'),
      nichePrompt('in a clubhouse locker room packing a golf bag, golf shoes and ankle socks, one foot on the bench, casual mid-chat expression, mixed fluorescent and window light, skin pores and natural uneven tone, a few loose hairs, open locker clutter and glove on the bench, candid phone framing with mild grain, lived-in not posed catalog'),
      nichePrompt('walking the fairway with a golf bag over one shoulder, sunglasses pushed up into hair, sun-kissed skin with visible pores and freckles on the shoulders, short hard sun shadow on the grass, a few windblown hairs, dusty bag strap digging into the shoulder fabric, full-body to three-quarter phone shot with mild wide-angle distortion and light grain, no beauty filter'),
      nichePrompt('mid-stride beside a lakeside hole, golf glove removed and held in one hand, satisfied soft smile, bright sun with specular on the water behind her, skin pores and slight forehead shine, flyaway hairs, wet grass stains near the shoe sole, three-quarter scenic phone framing with background bokeh and light grain, candid unposed'),
      nichePrompt('on a practice green in early morning dew, cardigan over a polo, coffee cup on the ground beside clubs, soft cool morning light with long gentle shadows, skin with visible pores and no makeup sheen, a few loose hairs, dew droplets on the putter and grass tips, quiet candid three-quarter phone photo with light grain, no airbrush'),
    ],
  },
  {
    id: 'gymnast',
    label: 'Gymnast',
    description: 'Chalk dust and leotards, balance-beam poise, competitive flexibility and grace.',
    defaultHairLock: 'tight competition bun with glitter hairspray sheen',
    prompts: [
      nichePrompt('balance beam mid-pose arms extended, sparkly competition leotard, chalk dust on hands'),
      nichePrompt('gym floor splits stretch, fitted leotard, focused warm-up expression'),
      nichePrompt('uneven bars chalk-covered grip, determined game-face concentration'),
      nichePrompt('locker room pre-meet nerves, leotard and warm-up jacket, tying hair into a bun'),
      nichePrompt('floor routine dramatic arch pose, sequined leotard catching light, arms overhead'),
      nichePrompt('vault runway sprint stance, focused eyes forward, chalk cloud behind'),
      nichePrompt('stretching circle team warm-up, leotard and grip straps, ankle wraps visible'),
      nichePrompt('medal podium moment, leotard and competition ribbon, proud emotional smile'),
      nichePrompt('training gym rings hanging pose, muscular definition, intense grip'),
      nichePrompt('backstage touch-up glitter makeup, hair slicked into competition bun'),
      nichePrompt('trampoline mid-air tuck pose, leotard flowing, weightless expression'),
      nichePrompt('cooldown foam roller gym corner, warm-up hoodie over leotard, tired satisfied glow'),
    ],
  },
  {
    id: 'hockey-girl',
    label: 'Hockey Girl',
    description: 'Rink-side grit, jerseys and skates, competitive winter-sport edge.',
    defaultHairLock: 'tight braid pulled through a helmet cage, ice-rink practical style',
    prompts: [
      nichePrompt('ice rink center face-off stance, team jersey and hockey pads, stick on ice'),
      nichePrompt('locker room pre-game lacing skates, jersey half zipped, focused pre-match energy'),
      nichePrompt('bench cooling down water bottle squeeze, helmet under arm, sweat-glow post-shift'),
      nichePrompt('rink boards leaning stick in hand, jersey untucked, confident smirk'),
      nichePrompt('practice drills puck handling, shin guards and jersey, intense concentration'),
      nichePrompt('post-game handshake line moment solo crop, jersey and gloves, tired proud smile'),
      nichePrompt('zamboni break ice rink empty behind, warm-up jacket over jersey, skates slung over shoulder'),
      nichePrompt('team photo pose solo crop, jersey number visible, stick resting on shoulder'),
      nichePrompt('parking lot arena bag over shoulder, hair damp from practice, casual hoodie'),
      nichePrompt('goal celebration arms up, jersey and pads, ice spray around skates'),
      nichePrompt('rink-side stretching pregame, compression gear and jersey, focused warm-up'),
      nichePrompt('locker room victory grin, jersey untucked, medal or puck trophy in hand'),
    ],
  },
  {
    id: 'volleyball-girl',
    label: 'Volleyball Girl',
    description: 'Sand and gym-court energy, athletic spikes, team-jersey confidence.',
    defaultHairLock: 'high ponytail with sweatband, sporty practical style',
    prompts: [
      nichePrompt('beach volleyball mid-serve leap, athletic bikini set, sand kicking up'),
      nichePrompt('indoor court dig stance low, team jersey and knee pads, intense focus'),
      nichePrompt('net mid-air spike pose, sports bra and shorts, powerful extension'),
      nichePrompt('sideline water break toweling off, jersey number visible, sweat glow'),
      nichePrompt('sand court sunset practice, bikini top and shorts, playful team huddle'),
      nichePrompt('locker room pre-match huddle solo crop, jersey and kneepads, game-face focus'),
      nichePrompt('gym bleachers stretching pre-game, athletic set, ankle brace visible'),
      nichePrompt('beach volleyball dive save, sand-covered knees, determined expression'),
      nichePrompt('team photo pose solo crop, jersey and shorts, hands on hips confident'),
      nichePrompt('post-win celebration jump, sweat-soaked jersey, joyful team energy'),
      nichePrompt('outdoor court serving stance, sun visor and athletic tank, focused aim'),
      nichePrompt('gym floor cooldown foam roller, kneepads and jersey, tired satisfied smile'),
    ],
  },
  {
    id: 'swim-dive',
    label: 'Swim & Dive',
    description: 'Pool-deck athleticism, competitive swimsuits, chlorine-glow discipline.',
    defaultHairLock: 'wet slicked-back hair, competitive swim-cap ready style',
    prompts: [
      nichePrompt('pool block start stance, competitive one-piece swimsuit, goggles on forehead'),
      nichePrompt('diving board edge toes gripping, focused pre-dive concentration, swim cap in hand'),
      nichePrompt('lane rope resting mid-lap, wet hair slicked back, goggle marks on face'),
      nichePrompt('locker room towel wrap post-practice, damp hair, medal around neck'),
      nichePrompt('pool deck stretching warm-up, team swimsuit, ankle stretch pose'),
      nichePrompt('underwater glide shot, streamlined swimsuit, bubbles trailing'),
      nichePrompt('starting blocks ready position, swim cap and goggles, intense focus forward'),
      nichePrompt('podium moment medal and towel, wet hair dripping, proud emotional smile'),
      nichePrompt('diving platform high board overlook, focused calm before the dive, swim cap on'),
      nichePrompt('team huddle poolside solo crop, matching swimsuits, water droplets on skin'),
      nichePrompt('sauna recovery post-meet, towel wrap, relaxed tired glow'),
      nichePrompt('open water swim wetsuit pulled to waist, sunrise lake backdrop, determined stance'),
    ],
  },
  {
    id: 'cheerleader',
    label: 'Cheerleader',
    description: 'Pom-poms and stadium lights, team spirit, high-energy sideline glam.',
    defaultHairLock: 'high sleek ponytail with team-color ribbon',
    prompts: [
      nichePrompt('stadium sideline pom-poms raised, pleated cheer skirt and crop top, big stadium-light smile'),
      nichePrompt('locker room pre-game hair and bow, cheer uniform half-zipped, mirror touch-up'),
      nichePrompt('football field mid-jump toe-touch, pom-poms mid-air, energetic pose'),
      nichePrompt('team huddle solo crop, matching uniform, hands stacked pep-talk energy'),
      nichePrompt('bleachers cheer routine formation, arms extended, crowd blur behind'),
      nichePrompt('practice gym mat stunt prep, cheer uniform and sneakers, spotter stance'),
      nichePrompt('game day tailgate face paint, cheer bow and uniform, playful pose'),
      nichePrompt('sideline kneeling formation pose, pom-poms crossed, focused game-watch'),
      nichePrompt('victory lap arms up with pom-poms, confetti falling, joyful celebration'),
      nichePrompt('school hallway uniform day, letterman jacket over cheer top, backpack slung'),
      nichePrompt('practice field splits stretch, uniform and sneakers, warm-up focus'),
      nichePrompt('post-game team photo solo crop, pom-poms held up, tired happy grin'),
    ],
  },
  {
    id: 'figure-skater',
    label: 'Figure Skater',
    description: 'Ice-rink elegance, sequined costumes, spins and edges, graceful competitive poise.',
    defaultHairLock: 'sleek competition bun with sparkling hairpins',
    prompts: [
      nichePrompt('ice rink spiral pose one leg extended, sequined skating costume, arms gracefully arched'),
      nichePrompt('rink-side lacing skates, warm-up jacket over costume, focused pre-program calm'),
      nichePrompt('spin combination mid-rotation blur, sparkly costume flowing, intense focus'),
      nichePrompt('podium moment medal and bouquet, costume and skates, emotional proud smile'),
      nichePrompt('practice rink stretching splits on ice, leg warmers over tights, warm-up focus'),
      nichePrompt('costume fitting mirror backstage, sequins catching light, hair being pinned'),
      nichePrompt('outdoor pond skating scenic, cozy sweater over leotard, playful glide'),
      nichePrompt('jump landing pose arms extended, costume skirt flaring, triumphant expression'),
      nichePrompt('rink boards leaning post-practice, skate guards on, tired satisfied smile'),
      nichePrompt('ice show group number solo crop, elaborate costume, graceful arm position'),
      nichePrompt('morning practice empty rink, simple practice dress, focused solitary skate'),
      nichePrompt('competition kiss-and-cry bench awaiting scores, warm-up jacket, anxious hopeful smile'),
    ],
  },
  {
    id: 'dubai-car-girl',
    label: 'Dubai Car Girl',
    description: 'Luxury car showroom life, supercars, desert skyline, high-end rental hustle glam.',
    defaultHairLock: 'long sleek glossy blowout, straight and polished with a designer headscarf option',
    prompts: [
      nichePrompt('showroom floor leaning against a matte black supercar, fitted blazer dress, showroom lights reflecting off the hood'),
      nichePrompt('supercar driver seat selfie, one hand on the wheel, sunglasses and gold jewelry, tinted windows'),
      nichePrompt('rooftop parking garage Dubai skyline behind, hand resting on a bright orange supercar door, wind in hair'),
      nichePrompt('desert highway pulled over beside a white convertible, headscarf and oversized sunglasses, dunes stretching behind'),
      nichePrompt('showroom key handoff moment, tailored pantsuit, keys dangling from manicured fingers, gleaming car row behind'),
      nichePrompt('gas station forecourt fueling a hypercar, casual luxury athleisure, sunglasses pushed up'),
      nichePrompt('hotel valet stand stepping out of a low sports car, evening gown, valet blurred in background'),
      nichePrompt('car wash detailing bay, silk shirt tied at waist, soapy supercar hood, playful candid smile'),
      nichePrompt('Palm Jumeirah villa driveway, sitting on the hood of a convertible, golden hour light'),
      nichePrompt('showroom glass office negotiating a rental, fitted dress and heels, paperwork and car keys on desk'),
      nichePrompt('night drive city lights streaking past windows, dashboard glow on face, confident hands on wheel'),
      nichePrompt('rooftop helipad backdrop, leaning on a matte-finish supercar, floor-length slit dress, skyline haze'),
    ],
  },
]
