/**
 * AUTO-GENERATED — do not edit by hand.
 * Source: MyGIF inspiration scrape (strict OF filter)
 * Generated: 2026-07-28T11:27:48.177Z
 * Niches: 6 | Prompts: 94
 *
 * Regenerate: npx tsx scripts/build-mygif-niches.ts
 */

import type { NicheDefinition } from '@/lib/niche-utils'

export const MYGIF_GENERATED_AT = "2026-07-28T11:27:48.177Z"

export const MYGIF_NICHE_DEFINITIONS: NicheDefinition[] = [
  {
    id: "mygif-of-mix",
    label: "MyGIF · OF Mix (All Buckets)",
    description: "Scraped MyGIF — balanced mix across tease, bedroom, close-up, selfie, pose. Source-tagged mygif; separate from brand niches.",
    prompts: [
      `Ultra realistic 4K photo of a woman in her early 20s, sitting on a light-colored wooden floor, back against the wall, hands naturally supporting her body on the floor on both sides, legs naturally extended. Camera angle is overhead moderate high angle shot, the woman looks up directly into the lens. Composition includes upper body, shoulders, collarbone, and part of the legs. She has long straight black hair, delicate facial features, a cool and gentle temperament. She wears a black silk spaghetti strap slip nightgown with lace trim, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman dreamy intimate portrait of a beautiful realistic asian woman lying under a blanket, soft natural light, cozy warm bedroom, cinematic film grain, 35mm film aesthetic, shallow depth of field, soft focus, delicate skin texture, natural makeup, slightly messy hair, Fujifilm Pro 400H look, pastel warm tones, realistic lighting, subtle haze, gentle atmosphere, by Petra Collins and Ren Hang, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman detailed portrait photography of a woman embodying 'pure desire' aesthetic, creating a gentle, hazy, and slightly mysterious atmosphere. The composition features the model positioned slightly to the right center, with a triangular composition formed by her shoulders, arms, and gaze. There is ample negative space on the left filled with white sheer curtains. The setting is minimalist with pure white sheer curtains as the main background, creating a dreamy, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman and emotionally charged female portrait photograph, blending the essence of Pure Seduction Aesthetic—retaining a cool, pure temperament while subtly revealing mature, sensual inner tension. The composition uses the rule of thirds with the subject centered slightly lower, direct eye contact, and negative space. The setting is a minimalist modern bedroom with white walls, light bedding, and abstract art. The model has deep brown wavy hair, natural makeup with smoky eyes and nude lips, and a confident, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman cool-toned East Asian woman, full-body standing portrait, short neat black hair with a few messy strands, subtle nude makeup, distant yet gentle expression, looking to the left side of the frame, wearing a beige minimalist lace sheer bra, with a loose translucent pearl white silk shirt slipping off her shoulders, paired with a white lightweight sheer fabric bottom, leaning against a plain warm beige matte wall, soft indoor side-backlighting creating a natural soft shadow of the figure on the wall, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman three beautiful young Asian women in pink bunny ear headbands posing seriously as bunnies: Left woman with long straight black hair, doe eyes, smokey makeup, red lips in sultry pout, sitting with knees bent, legs crossed, hand on thigh; middle with shoulder-length hair and bangs, dramatic eyeliner, neutral expression, kneeling upright with hands on knees; right with chin-length bob and bangs, cat eyes, enigmatic gaze, sitting with one knee raised, arms hugging knees. All in white lace bodysuits with deep V-necks, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman focusing on her back and side profile, wearing a white sheer dress with a bow at the waist. The composition uses the rule of thirds, with a simple light brown background. Soft lighting from the front left creates shadows on the back, enhancing depth. The woman has an elegant updo, subtle makeup, and gazes into the distance. Shot with a medium telephoto lens, low angle, and post-processed for warm tones, contrast, and smooth skin, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman and emotionally tense female portrait photography, exemplifying the 'pure desire' style. The overall image presents a gentle, hazy, and secretly desirous aesthetic atmosphere, achieved through the exquisite combination of lighting, composition, clothing details, and posture, creating a subtle yet alluring visual experience. The composition focuses on a close-up of the woman's upper body, particularly the chest area, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman capturing her softness and sensuality. The composition features an asymmetrical layout with the woman's face on the right and her arm and clothing on the left, against a dark blurred background. The atmosphere is warm and intimate, with soft lighting from the side highlighting skin texture and white clothing. The woman has natural makeup, wet hair, and a thoughtful expression, with her arm slightly raised and fingers gently touching. The shot uses a close-up perspective with a longer focal length for bokeh effect, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman standing confidently in a minimalist studio, shot from a slightly low angle, half-body portrait, her head tilted slightly down with a calm and enigmatic expression, middle-parted braided pigtails with a few loose strands falling over her face, subtle wet hair texture, wearing a tight black sleeveless dress and black leather gloves, holding a leather belt loosely in front of her body — dramatic single key light from upper right, high contrast, black and white tones, strong rim light accentuating her curves, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman hyperrealistic female portrait of a female character standing in a completely black background. Lighting: use a narrow beam spotlight focused only on the center of the face and mouth. The edges of the light must be sharp and dramatic. All areas outside the spotlight should fall quickly into deep darkness (high falloff shadow), almost blending into the black background. Not soft lighting. Hair: long dark hair, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman 35mm color film photography with harsh direct on-camera flash, specular highlights on skin and clothing, strong catchlights in eyes, high contrast flash illumination, authentic film grain and color shift, high fashion fresh innocent basketball court editorial style, intimate first-person low-angle POV shot from below, early 20s sexy Chinese female idol with ultra-realistic delicate refined Chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp V-shaped jawline, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman sophisticated Japanese female model in pastel pink off-shoulder bikini, sitting pose, airy sunlight through curtains, elegant beauty editorial, soft romantic tones, minimal luxury interior, premium fashion catalog photography, no text, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman young Japanese idol in a swimsuit on a tropical beach, her hair in pigtails and bangs hanging over her eyes, gazes out at the sea with a calm expression. One hand is behind her back, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman photorealistic cinematic natural light portrait, vertical composition, half-body side profile of a young adult East Asian woman. She stands by a bright window, head slightly bowed, eyes cast downward, expression serene and vulnerable. Loose black hair in a low bun with strands softly illuminated by warm backlight. Elegant neck and shoulder lines, clavicle visible. She wears a lightweight cream off-shoulder dress with natural flowing folds, left shoulder fully exposed, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman young Japanese beauty in a stylish maid-inspired outfit outdoors, three-quarter portrait (from lower legs upward), elegant body framing and balanced proportions. Long wavy light-brown hair with airy texture, white maid headband. Soft K-beauty makeup: peach-pink eyeshadow with subtle shimmer, long curled lashes, delicate eyeliner, warm hazel circle lenses giving a doll-like enlargement, rosy blush, rose-pink gradient velvet matte lips. Outfit: black and white maid dress with puff sleeves, sailor-style collar, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman stealthy candid capture from a close-up front angle of a beauty applying makeup in a vanity mirror, short bob haircut with layered bangs framing her face, dewy skin and pouty lips, in a silky robe slipping slightly, soft bathroom lighting with steam haze for a personal morning routine feel, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman cinematic portrait of a young asian woman sitting on grass outdoors, soft direct gaze to camera, natural pose with slightly leaning forward posture, wearing a loose white shirt, dark skirt, gentle wind moving her hair, minimal background with soft blur, calm and dreamy atmosphere, intimate and emotional tone lighting: strong backlight from low golden hour sun directly behind subject, sunlight creating a glowing halo around hair (rim light), soft flare bleeding into lens, warm sunlight wrapping around face, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman wearing a vintage red wedding dress with a classic retro hairstyle, seen through a mirror, gently applying lip color with a small compact while looking at her reflection, calm and slightly melancholic expression, natural freckles and soft facial features, dim interior space with a quiet, intimate atmosphere, a hint of window light softly entering the scene, parts of her face and surroundings fading into shadow, foreground elements like the mirror edge or soft shapes partially obscuring the view, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman 25-year-old Japanese girl in a swimsuit, breaking physical reality and scale, with visual metaphors, spatial illusions, and storytelling, inspired by international advertising award creativity, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
    ],
  },
  {
    id: "mygif-bedroom-lingerie",
    label: "MyGIF · Bedroom / Lingerie",
    description: "Scraped MyGIF — bedroom, lingerie, silk, private intimacy.",
    prompts: [
      `Ultra realistic 4K photo of a woman in her early 20s, sitting on a light-colored wooden floor, back against the wall, hands naturally supporting her body on the floor on both sides, legs naturally extended. Camera angle is overhead moderate high angle shot, the woman looks up directly into the lens. Composition includes upper body, shoulders, collarbone, and part of the legs. She has long straight black hair, delicate facial features, a cool and gentle temperament. She wears a black silk spaghetti strap slip nightgown with lace trim, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman dreamy intimate portrait of a beautiful realistic asian woman lying under a blanket, soft natural light, cozy warm bedroom, cinematic film grain, 35mm film aesthetic, shallow depth of field, soft focus, delicate skin texture, natural makeup, slightly messy hair, Fujifilm Pro 400H look, pastel warm tones, realistic lighting, subtle haze, gentle atmosphere, by Petra Collins and Ren Hang, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman detailed portrait photography of a woman embodying 'pure desire' aesthetic, creating a gentle, hazy, and slightly mysterious atmosphere. The composition features the model positioned slightly to the right center, with a triangular composition formed by her shoulders, arms, and gaze. There is ample negative space on the left filled with white sheer curtains. The setting is minimalist with pure white sheer curtains as the main background, creating a dreamy, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman and emotionally charged female portrait photograph, blending the essence of Pure Seduction Aesthetic—retaining a cool, pure temperament while subtly revealing mature, sensual inner tension. The composition uses the rule of thirds with the subject centered slightly lower, direct eye contact, and negative space. The setting is a minimalist modern bedroom with white walls, light bedding, and abstract art. The model has deep brown wavy hair, natural makeup with smoky eyes and nude lips, and a confident, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman cool-toned East Asian woman, full-body standing portrait, short neat black hair with a few messy strands, subtle nude makeup, distant yet gentle expression, looking to the left side of the frame, wearing a beige minimalist lace sheer bra, with a loose translucent pearl white silk shirt slipping off her shoulders, paired with a white lightweight sheer fabric bottom, leaning against a plain warm beige matte wall, soft indoor side-backlighting creating a natural soft shadow of the figure on the wall, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman three beautiful young Asian women in pink bunny ear headbands posing seriously as bunnies: Left woman with long straight black hair, doe eyes, smokey makeup, red lips in sultry pout, sitting with knees bent, legs crossed, hand on thigh; middle with shoulder-length hair and bangs, dramatic eyeliner, neutral expression, kneeling upright with hands on knees; right with chin-length bob and bangs, cat eyes, enigmatic gaze, sitting with one knee raised, arms hugging knees. All in white lace bodysuits with deep V-necks, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman extreme close-up high-key beauty editorial portrait of an adult woman, camera positioned very close behind her and slightly below the shoulder line, angled upward along the bare back toward the neck, jaw, ear cuff, and side profile. Pearl-white studio backlight, cool gray mist filter, low contrast, soft overexposed highlights, faint bloom, subtle film grain, realistic skin texture. Subject: an elegant woman turned away from the camera, full bare upper back visible, chest completely hidden by body angle and crop, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman sTYLE: Smartphone direct flash bedroom snapshot Raw social media realism Harsh on-camera flash Visible grain in shadows No cinematic grading Aspect ratio 4:5 vertical -------------------------------------- SUBJECT: Adult feminine subject from reference image Sitting sideways on a messy bed Weight resting naturally on one hip One hand raised making a peace sign near her face Slightly lowered playful gaze Tongue sticking out slightly in a carefree expression Flirty but casual, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman chinese female portrait in pure desire style, expressing sensuality without nudity, with a cute face, subtle makeup, full curves, and realistic skin texture with visible pores. The image is highly artistic and emotionally charged, featuring a woman leaning against a wall with natural light creating dramatic shadows, using an 85mm or 100mm lens for shallow depth of field, and processed with 16K resolution for a realistic photographic look. The composition uses diagonal lines and the rule of thirds, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman seductive stunning & beautiful 20-year-old Japanese or Korean woman, tall slim elegant hourglass figure with balanced proportions, small sculptural hoop earring detail, seated pose with both hands placed behind for support, sharp delicate V-line jaw and tapered chin, petite symmetrical oval face, side-parted collarbone-length waves, soft flowing texture, deep coffee-brown hair, looking directly at the camera. She wearing off-white open slightly oversized cropped leather jacket, unfastened moto jacket, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman natural grab shot of an alluring day-style woman hiking in the mountains, ponytail with bangs, flushed cheeks from exertion, in a sports bra top and leggings, pausing to look at the view, misty background with slight fog, captured mid-step for dynamic feel, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman high-key portrait of a young East Asian woman with fair skin and long dark chocolate brown hair in loose waves. She kneels on a plush white shag rug, looking over her shoulder directly at the camera with a sultry gentle smile. Wearing a champagne-colored silk slip dress. Soft diffused window light from side-back position creates rim lighting and flattering highlights. Shot with 85mm f/1.4 lens, shallow depth of field, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman simple and intimate portrait photo in Japanese film photography style, with an extremely strong dreamy soft-focus effect. Bright sunlight streams into the bedroom, creating rich lens flare and ethereal glow, significantly enhancing highlights and softening edges. A sexy young Japanese woman in a white sheer lace camisole leans on the bed; the soft focus makes her figure slightly blurred, adding a romantic touch. The air is filled with a hazy, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman professional sportswear product photography pose guide, East Asian female model, dark gray/black yoga set (sports bra + high-waisted leggings), clean studio background, soft natural light. Collage layout: 2 rows × 5 columns, each pose with Chinese captions. 10 poses: 1. Standing S-shape, one hand in pocket, looking into the distance; 2. Standing with crossed legs, one hand brushing hair, looking at the camera with a smile; 3. Leaning against the wall with arms crossed, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman prompt： { "theme": "Silk Slip Dress / Backlit S-Curve Dream", "subject_archetype": "K-Pop Goddess with Porcelain Skin.", "outfit": "Pearl-white silk slip dress, very thin straps, soft draping neckline.", "pose": "Kneeling sitting on soft white bedding, body turned sideways to camera. Back slightly arched showing the S-line from bust to hip. Looking back over shoulder with an innocent, sleepy expression.", "lighting": "Strong backlight from a window (逆光), shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman ultra-realistic cozy bedroom portrait of a beautiful Korean woman sitting on her bed at night, turning slightly over her shoulder toward the camera with a soft shy smile, wearing an oversized fluffy pastel pink hoodie. Long silky black hair flowing naturally down her back, glossy eyes, soft blushy makeup, natural skin texture, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman photorealistic portrait of a young woman with shoulder-length, textured wavy light brown hair and soft, natural makeup with rosy cheeks. She is standing in a vibrant, bright yellow-themed bedroom. She is wearing an oversized yellow hoodie featuring a graphic of Pikachu's face and a matching yellow beanie with a Pikachu face on it. She is holding a large, fluffy Pikachu plush toy with big round eyes, red cheeks, and a happy expression. Behind her, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman close-up headshot portrait of a woman lying prone on a bed, gazing intimately at the camera with a sultry expression, finger touching her glossy lips. Her face is illuminated by the cool blue/violet glow of a screen (phone or computer) in a dark room. She has messy dark hair, flushed cheeks, and wears a black lace camisole. The background features a grey patterned pillow, curtains, and deep shadows. The mood is intimate, late-night, vulnerable, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman prompt: A beautiful, sensual blond woman doing Pilates, shown as a 2×2 grid collage on a 4:5 canvas. Each panel is a low-quality smartphone photo, casual and unpolished, as if taken during a workout break. elegant facial features, and a calm yet confident presence. Her expression is focused and relaxed, not posed for a professional shoot. Outfit (same in all frames): Gray tight shorts White sports bra with a deep neckline Simple, realistic gym wear, slightly wrinkled, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman edit this photo without changing her facial features. This is a close-up photo from the chest up of a young, beautiful, fair-skinned woman. The image shows her in a bedroom at night, lit by a bright internal flash that creates a sharp highlight on her face and hair. Her short, black hair falls beautifully in slight waves, with a soft expression on her face. The flash accentuates the dimly lit living room background. The shot is candid, raw, nostalgic, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman 65A photorealistic portrait of a young woman with long, wavy brunette hair resting her chin gently on her hand. She is wearing a cozy, teal cable-knit sweater and a wristwatch with a white strap. She is sitting at a white marble table by a window, bathed in warm, golden-hour sunlight coming from the left, highlighting her face and hair. In the foreground, there is a white ceramic coffee cup, a small vase with soft pink and white roses, and a smartphone lying on the table. The background is a soft-focus interior, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman モデルが軽いランジェリーを身に着け、慎重に採寸される静かな試着室のシーン。柔らかな照明で落ち着いたプロフェッショナルな雰囲気を演出します。 A quiet fitting room scene where a model stands in light lingerie as measurements are carefully taken, creating a calm, professional atmosphere with soft lighting, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman prompt: A 2×2 instructional pose comparison grid, designed to teach how to pose vs. how not to pose. The image is divided into four equal panels, each panel containing a vertically oriented portrait photo (3:4 ratio) of the same slim female model, photographed in the same location, lighting, and outfit for direct comparison. Model & Appearance: Slender woman with long dark hair pulled back, minimal makeup, neutral expression. Athletic yet feminine build, natural proportions, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman soft, dreamy 4-photo collage of a young woman with long, straight black hair in a minimal, modern bedroom setting. She wears a sleeveless crochet knit top with delicate texture, light blue jeans with subtle worn details, and casual white sneakers. Each frame shows her in different relaxed, natural poses: sitting on the bed with legs folded, leaning forward thoughtfully, resting with arms gently crossed, and gazing directly into the camera with an introspective, dreamy expression. Warm, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
    ],
  },
  {
    id: "mygif-tease-implied",
    label: "MyGIF · Tease / Pure Desire",
    description: "Scraped MyGIF — flirty tease, sensual implied, pure-desire mood.",
    prompts: [
      `Ultra realistic 4K photo of a woman focusing on her back and side profile, wearing a white sheer dress with a bow at the waist. The composition uses the rule of thirds, with a simple light brown background. Soft lighting from the front left creates shadows on the back, enhancing depth. The woman has an elegant updo, subtle makeup, and gazes into the distance. Shot with a medium telephoto lens, low angle, and post-processed for warm tones, contrast, and smooth skin, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman and emotionally tense female portrait photography, exemplifying the 'pure desire' style. The overall image presents a gentle, hazy, and secretly desirous aesthetic atmosphere, achieved through the exquisite combination of lighting, composition, clothing details, and posture, creating a subtle yet alluring visual experience. The composition focuses on a close-up of the woman's upper body, particularly the chest area, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman capturing her softness and sensuality. The composition features an asymmetrical layout with the woman's face on the right and her arm and clothing on the left, against a dark blurred background. The atmosphere is warm and intimate, with soft lighting from the side highlighting skin texture and white clothing. The woman has natural makeup, wet hair, and a thoughtful expression, with her arm slightly raised and fingers gently touching. The shot uses a close-up perspective with a longer focal length for bokeh effect, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman standing confidently in a minimalist studio, shot from a slightly low angle, half-body portrait, her head tilted slightly down with a calm and enigmatic expression, middle-parted braided pigtails with a few loose strands falling over her face, subtle wet hair texture, wearing a tight black sleeveless dress and black leather gloves, holding a leather belt loosely in front of her body — dramatic single key light from upper right, high contrast, black and white tones, strong rim light accentuating her curves, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman hyperrealistic female portrait of a female character standing in a completely black background. Lighting: use a narrow beam spotlight focused only on the center of the face and mouth. The edges of the light must be sharp and dramatic. All areas outside the spotlight should fall quickly into deep darkness (high falloff shadow), almost blending into the black background. Not soft lighting. Hair: long dark hair, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman 35mm color film photography with harsh direct on-camera flash, specular highlights on skin and clothing, strong catchlights in eyes, high contrast flash illumination, authentic film grain and color shift, high fashion fresh innocent basketball court editorial style, intimate first-person low-angle POV shot from below, early 20s sexy Chinese female idol with ultra-realistic delicate refined Chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp V-shaped jawline, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman use same face 100% Ultra realistic portrait of a glamorous young girl, same face as reference. She wears a thin high neck white dress with a luxurious blue fur coat draped over her shoulders. Accessories: single pearl necklace. Hairstyle: elegant messy high top bun with a few loose strands framing the face. Makeup: flawless matte skin, soft blush, sharp eyeliner, natural pink lips. Expression: confident and alluring, Background: soft gray gradient studio lighting, cinematic fashion editorial, Revealing her, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman pure desire style female portrait photography, featuring a young woman in a beige off-shoulder knit sweater against a minimalist light gray background, with soft lighting from the left side, natural makeup, deep brown hair in a low ponytail, and an elegant pose with hands crossed. The image uses a medium telephoto lens, shallow depth of field, and professional editing for color balance, sharpness, and skin retouching, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman pure desire style Chinese female portrait, emphasizing alluring curves and full bust without nudity, with a cute face, subtle makeup, and fine skin texture visible pores, 16K, realistic photography. The scene is a night market stall with foreground cooking utensils and blurred background lights, capturing a sensual yet non-explicit expression with high hormonal tension. The composition uses the rule of thirds, shallow depth of field, and mixed lighting to create a visual impact. The woman has short black hair, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman spontaneous photo of a sexy day-vibe woman on a subway train, long dark hair with straight bangs, fair complexion, wearing a cropped camisole and mini skirt, gazing out the window dreamily, motion blur from the moving train, reflective glass adding depth, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman 1. Composition: Vertical portrait, extreme close-up head and shoulders, subject positioned to the right occupying a large proportion of the frame. 2. Perspective: Eye-level frontal close-up, slight central symmetry, direct eye contact with the camera. 3. Depth of Field: Cleanly blurred background, sharp and clear facial features and eyes, visible hair strand details. 4. Subject Reference: Strictly based on the uploaded reference image for identity. Zero deviation required. 5. Character: Young woman, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman 35mm film photography, warm vintage Japanese onsen ryokan aesthetic, soft ambient wooden lantern lighting mixed with gentle natural window light, subtle film grain, gentle color shift, high atmosphere editorial style, intimate medium shot, early 20s beautiful Chinese female idol with ultra-realistic delicate refined Chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp V-shaped jawline, flawless porcelain skin with warm ivory undertone, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman typical 'pure desire' style female portrait photography, showcasing soft, natural lighting effects and delicate emotional expression. The image features a young woman sitting on a sofa with lace curtains in the background, creating a gentle, romantic atmosphere with subtle shadows and highlights. The composition uses a medium shot with the subject slightly off-center, and the lighting is natural from a window, filtered through the curtains to produce a dreamy effect. The post-processing includes warm tones, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman 35mm film photography with harsh convenience store fluorescent lighting mixed with colorful neon signs from outside, authentic film grain, high contrast, slight color cast, cinematic street editorial style, intimate medium shot, early 20s sexy Chinese female idol with ultra-realistic delicate refined Chinese features, seductive almond-shaped fox eyes with natural double eyelids, high nose bridge, small sharp V-shaped jawline, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman japanese street portrait at night, candid photography, direct flash mixed with ambient street lighting, harsh frontal flash with deep shadow falloff, slight motion blur, imperfect focus, raw snapshot aesthetic a stunning beautiful japanese woman walking alone on a quiet street at night, subtle wind moving her hair, natural unposed movement, mid-step or slight pause, not aware of camera hair: natural black hair, slightly messy, wind-blown strands across face, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman low-light cinematic portrait, telephoto lens compression, shallow depth of field, intentional soft focus and motion blur, moody nightlife atmosphere, abstract storytelling composition, layered haze and diffusion, imperfect candid capture a stunning beautiful Korean female idol, ultra high visual appeal, pale porcelain skin, delicate yet seductive features, effortlessly alluring presence, relaxed and slightly tipsy mood, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman with a blend of Eastern aesthetics and modern pure desire style. She has black hair neatly tied up with a pearl hairpin, wearing a coral orange qipao with a pearl button. The composition uses the rule of thirds, with the subject on the right, looking left, and a warm orange gradient background featuring subtle plum blossom patterns. Lighting includes a main soft light from the right front at 45 degrees and a contour light from the left back, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman editorial fashion portrait, 3:4 vertical aspect ratio, Korean female idol, early 20s, YG/BLACKPINK aesthetic, fox eyes with heavy-lidded sultry gaze, sharp jawline V-line, heart-shaped face, high nose bridge, full lips slightly parted, cold white skin with subtle sweat sheen on collarbones and shoulders, smoky gold-bronze eyeshadow, dramatic cat eyeliner, bold wine-red glossy lips, long dark hair with subtle golden highlights, slightly messy wet-look styling, hair partially falling over face and shoulders, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman this prompt creates a different visual in each vehicle. While Grok created a face portrait and a banana ordinary photograph, the images created by Whisk were interesting to me. In addition, changes in exposure and posture or clothing are automatic. So the prompt creates a random editorial image. 🥰 GLOBAL STYLE & QUALITY Ultra high-end hyper realistic cinematic fashion photography. High-budget film still realism, dramatic color grading, luxury editorial intensity. Zero illustration feel, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman and emotionally deep female portrait in the pure desire aesthetic style, showcasing a balance of restrained beauty and inner desire. The composition uses the rule of thirds and golden ratio, with the subject positioned on the right side against a pure black background. The lighting features soft side light with a 45-degree angle, creating gentle shadows and highlights on the face, neck, and shoulders. The subject wears a loose white shirt, with subtle makeup and natural hairstyle, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman impactful and artistically expressive female portrait photography, blending the essence of Pure & Seductive style. It features a woman in an off-shoulder multicolored shirt, holding a silver spoon lightly against her lips, with a playful yet mysterious expression. The background consists of high-saturation mosaic color blocks in red, yellow, blue, green, purple, and pink, creating a pop art aesthetic. The composition uses a medium close-up with the subject slightly off-center, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman portrait in pure desire style, blending innocence with subtle sensuality. The image should feature a woman with long wavy hair, soft makeup, and a white tank top, set against a dark green background. Use studio lighting with key light, fill light, and rim light to create a cinematic effect, emphasizing warm skin tones and cool background contrast. The composition follows the rule of thirds, with the subject positioned to the right, and shallow depth of field for focus. The mood is calm yet evocative, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman japanese negative film aesthetic, rooftop summer scene, soft natural sunlight, slight overexposure highlights, low contrast, muted faded colors, subtle grain a stunning beautiful young woman with subtle sensual presence, natural body line, effortless charm wearing a slightly oversized white shirt loosely unbuttoned at the collar, paired with high-waisted shorts; shirt softly moving in the wind, occasionally slipping off one shoulder holding a cold glass bottle drink with condensation, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman in a new Chinese pure desire style, blending oriental aesthetics with modern sensuality. The woman has a classical hairstyle and wears a light green silk cheongsam with pearl buttons. She holds a translucent fan that partially covers her face, creating a mysterious and poetic atmosphere. The background features blurred bamboo leaves and green plants, with soft lighting that includes key light, fill light, and rim light to enhance depth and emotion. The overall tone is warm with a hint of green, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman cinematic 6-frame grid (3x2), ultra-luxury fashion campaign inspired by Saint Laurent, featuring a dramatic vert turquoise ruffled nylon gown, strong editorial composition, STRICT consistency across all frames, same color grading, same lighting style, same cinematic tone lighting: hard flash + deep shadows + moody tungsten tones, high contrast, slightly overexposed highlights on skin, dark background falloff color palette: black, deep red, emerald turquoise, burnt gold, warm skin tones, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman studio portrait photograph, close-up of the mid-bust (from the chest up), with a high-fashion, glamorous, and striking aesthetic. The female figure is positioned frontally, with her head tilted slightly back and her chin raised, looking straight ahead with a serious, confident, and seductive expression. Her lips are half-parted, adding a touch of mystery and sensuality. The composition is clean, dramatic, and focuses intensely on the face and glasses, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman japanese negative film aesthetic, Ricoh GR III street photography style, night direct-flash photography, photorealistic influencer-style fashion portrait, candid social-media snapshot feeling, close-up to half-body composition, low-angle upward shot capturing a relaxed stretching motion, slightly tilted framing, razor-sharp focus on the subject with soft imperfect focus falloff, shallow depth of field, harsh direct flash on skin and lace fabric, glossy flash highlights, dark tropical night background, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman an elegant woman blending Eastern aesthetics with modern photography, featuring a pure desire style with subtle sensuality. The woman is in a white translucent qipao, holding a green silk fan with floral patterns, set against a backdrop with bamboo shadows and soft lighting. Use classic composition with rule of thirds, shallow depth of field, and gentle lighting from the front and side. The image should convey a serene, poetic mood with restrained emotion and delicate details in hair, makeup, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
    ],
  },
  {
    id: "mygif-intimate-closeup",
    label: "MyGIF · Intimate Close-up",
    description: "Scraped MyGIF — face / collarbone / tight portrait framing.",
    prompts: [
      `Ultra realistic 4K photo of a woman sophisticated Japanese female model in pastel pink off-shoulder bikini, sitting pose, airy sunlight through curtains, elegant beauty editorial, soft romantic tones, minimal luxury interior, premium fashion catalog photography, no text, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman young Japanese idol in a swimsuit on a tropical beach, her hair in pigtails and bangs hanging over her eyes, gazes out at the sea with a calm expression. One hand is behind her back, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman photorealistic cinematic natural light portrait, vertical composition, half-body side profile of a young adult East Asian woman. She stands by a bright window, head slightly bowed, eyes cast downward, expression serene and vulnerable. Loose black hair in a low bun with strands softly illuminated by warm backlight. Elegant neck and shoulder lines, clavicle visible. She wears a lightweight cream off-shoulder dress with natural flowing folds, left shoulder fully exposed, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman young Japanese beauty in a stylish maid-inspired outfit outdoors, three-quarter portrait (from lower legs upward), elegant body framing and balanced proportions. Long wavy light-brown hair with airy texture, white maid headband. Soft K-beauty makeup: peach-pink eyeshadow with subtle shimmer, long curled lashes, delicate eyeliner, warm hazel circle lenses giving a doll-like enlargement, rosy blush, rose-pink gradient velvet matte lips. Outfit: black and white maid dress with puff sleeves, sailor-style collar, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman stealthy candid capture from a close-up front angle of a beauty applying makeup in a vanity mirror, short bob haircut with layered bangs framing her face, dewy skin and pouty lips, in a silky robe slipping slightly, soft bathroom lighting with steam haze for a personal morning routine feel, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman cinematic portrait of a young asian woman sitting on grass outdoors, soft direct gaze to camera, natural pose with slightly leaning forward posture, wearing a loose white shirt, dark skirt, gentle wind moving her hair, minimal background with soft blur, calm and dreamy atmosphere, intimate and emotional tone lighting: strong backlight from low golden hour sun directly behind subject, sunlight creating a glowing halo around hair (rim light), soft flare bleeding into lens, warm sunlight wrapping around face, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman "prompt": "A high-angle, close-up portrait photograph taken from directly above, capturing the person I uploaded looking straight up with a soft, neutral expression. She has long, shoulder-length black hair in a ponytail and fair skin with prominent natural freckles across her nose, cheeks, and forehead. Her eyes with long dark lashes make direct eye contact. She is wearing a yellow off-shoulder sleeveless top with ruffle details, a deep V-neck, multiple gold and diamond rings on her fingers, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman prompt - A young Japanese beauty model glamour hot in a stylish black streped jeans with shorts chiaroscuro black outfit outdoors short jeans , three-quarter portrait (from lower legs upward), elegant body framing and balanced proportions. Long wavy light browny hair with airy texture Soft K-beauty makeup: peach-pink eyeshadow with subtle shimmer, long curled lashes, delicate eyeliner, warm hazel circle lenses giving a doll-like enlargement, rosy blush, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman use the reference image only; keep facial geometry 100% identical. Ultra-realistic night fashion shot on a balcony. Glamorous woman in deep red satin strapless mini dress, corset bodice, ruffled skirt. Glossy waves, bold red lips, gold hoops. Leaning on railing, eyes closed. Direct flash, dark city background, sharp 4K detail, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman ultra-realistic portrait of the same beautiful Korean girl from the previous images, maintaining the exact same facial appearance, soft Korean beauty aesthetic, glossy eyes, natural blush makeup, silky long black hair, youthful features, and realistic skin texture consistency. She is standing inside a quiet Japanese city bus during daytime, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman ultra-realistic cozy Korean kitchen portrait of a beautiful Korean woman standing beside the kitchen counter at night, slightly turning toward the camera with a soft playful smile while holding a metal whisk above her shoulder. Wearing an oversized fluffy pastel pink hoodie, sleeves covering part of her hands, cozy feminine aesthetic. Long silky black hair flowing naturally, glossy eyes, soft blush makeup, natural skin texture, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman dramatic close-up portrait of a couple standing intimately close, captured in warm golden-hour light that highlights the wet strands of the woman’s hair and the soft texture of their skin. The woman gazes forward with striking confidence, her bold red lips and expressive eyes illuminated with cinematic depth. The man leans in gently with closed eyes, creating a sense of emotional closeness and quiet tension. Sunlight outlines their faces, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman high-quality, photorealistic portrait of a young woman with long, straight dark hair pinned back with a pink hair clip. She is wearing a beige knit sweater with a red geometric pattern. She is resting her chin on her crossed arms, leaning on an open hardcover book on a wooden desk. The background is a blurred library setting with bookshelves and warm, glowing fairy lights creating a soft bokeh effect. In the immediate foreground, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman hyper-realistic photo of a slender and elegant Asian woman in her mid-20s with a gentle, contemplative expression, gazing towards the right. She has dark brown hair in a messy bun with soft wisps, minimalist natural makeup with soft pink lips and light blush. She wears a white open-knit crochet cardigan with long flared sleeves and pastel floral appliques (yellow, blue, pink), a white string bikini top and bottom, delicate multi-strand beaded necklaces in pastel colors, a body chain, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman "A surreal, fashion-forward studio portrait photograph, 9:13 vertical aspect ratio, featuring a beautiful woman in a stunning, intricate gown with striking, beautiful eyes, framed in a close, tight-angled composition from the chest up. The lighting is architectural and experimental, as per the template. The woman, with a relaxed yet intentional pose, shoulders turned and head angled in a three-quarter view, looks assertively past the lens with a calm, confident, and modern expression, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman a hyper-realistic portrait of a cute Asian woman .She is sitting and resting her chin on her hand at a dark wooden table in a vintage-style room. Fashion & Outfit: She wears a red-and-white plaid puff-sleeve crop top with a wide neckline that shows her collarbones and a bit of cleavage. The top has small lace ruffle details along the edges and a ribbon bow tied at the center of the chest. She pairs it with a matching fitted mini skirt. She wears a minimalist necklace with a small pendant. Background: A corner insid, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman dramatic, close-up, studio portrait of a woman with high-glamour makeup (strong winged eyeliner, defined contour matte nude-brown lipstick). She has short wavy brown hair and is wearing a wide-brimmed black fedora or hat and a black blazer. She is accessorized with multiple strands of layered pearl necklaces and a pearl ring. She holds a large, pristine white peony flower close to her face. The background is a solid, dark charcoal gray/black, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman [Key: Maintain precise facial features, retain original facial structure, the character in the image is completely consistent with the uploaded reference image] Full-body portrait of a person, showcasing porcelain-smooth fair skin and subtle makeup. She wears a modern gold sequin crop top paired with white high-waisted wide-leg pants, with a red long cardigan over it, presenting a fashionable New Year's Eve outfit. Long straight hair falls naturally, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman high-end luxury lifestyle editorial photograph set inside an upscale modern billiards lounge. The scene captures a candid over-the-shoulder moment of a stylish young woman leaning forward as she prepares to take a precise pool shot. Her posture is relaxed yet confident, reflecting effortless elegance. Her hair is styled in a soft low bun secured with a plush designer-style hair clip, subtly luxurious and natural. She wears a minimalist dark top with clean tailoring, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
      `Ultra realistic 4K photo of a woman cheerful girl standing in the shallow ocean water on a sunny beach day, wearing a fitted blue rash guard crop top and white shorts, her hair tied back in a ponytail adorned with colorful ribbons, captured in a side view while smiling brightly and striking a playful double peace sign pose, the sunlight reflecting off the gentle waves around her, creating sparkling highlights on the water surface, highly detailed and realistic water texture with small ripples and foam, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
    ],
  },
  {
    id: "mygif-soft-selfie",
    label: "MyGIF · Soft Selfie / Mirror",
    description: "Scraped MyGIF — mirror and phone-camera selfies.",
    prompts: [
      `Ultra realistic 4K photo of a woman wearing a vintage red wedding dress with a classic retro hairstyle, seen through a mirror, gently applying lip color with a small compact while looking at her reflection, calm and slightly melancholic expression, natural freckles and soft facial features, dim interior space with a quiet, intimate atmosphere, a hint of window light softly entering the scene, parts of her face and surroundings fading into shadow, foreground elements like the mirror edge or soft shapes partially obscuring the view, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
    ],
  },
  {
    id: "mygif-outfit-seasonal",
    label: "MyGIF · Outfit / Seasonal",
    description: "Scraped MyGIF — bikini, summer, outfit drops.",
    prompts: [
      `Ultra realistic 4K photo of a woman 25-year-old Japanese girl in a swimsuit, breaking physical reality and scale, with visual metaphors, spatial illusions, and storytelling, inspired by international advertising award creativity, shot on iPhone, natural lighting, neutral color balance, candid unposed realism, subtle contrast, authentic smartphone photography.`,
    ],
  }
]

/** Original MyGIF inspiration ids per niche (debug / provenance). */
export const MYGIF_SOURCE_IDS: Record<string, string[]> = {
  "mygif-of-mix": ["insp_mpuz1nmtjsswaq","336","insp_mjcp2plu1ncsfg","insp_miyob5xb5lwkf9","insp_mqazvy9qwuh76f","insp_mh98wpbdlis8nw","insp_miq44cdia88o0q","insp_mizky9lrt5qnc5","insp_miq3h65dhlhxdh","insp_mh1sfhf884ygcc","insp_mix8axa23qy05l","insp_4925af058b14f44f","insp_mozc0ujhqp7mg2","insp_mkqme6mhssv41s","insp_mpc5m3ryp055z8","insp_misdsvfofrbvnv","insp_mhrpteeer511yp","insp_mny31s6l06pfib","insp_mn90biscb4zg9t","insp_mq5aocz3b49a2y"],
  "mygif-bedroom-lingerie": ["insp_mpuz1nmtjsswaq","336","insp_mjcp2plu1ncsfg","insp_miyob5xb5lwkf9","insp_mqazvy9qwuh76f","insp_mh98wpbdlis8nw","insp_mpr2inn53dkofe","insp_mmfr0rb4v4c6bs","insp_miq2z0t07dy685","insp_mpc6kd6y8zlzuc","insp_mhrq89cxtulehy","insp_mh0jkbtu4djv8z","insp_mjleszw4a1d9my","insp_milnv48eo9ac2p","insp_mkhs38of95v14r","insp_mp6km0567tzwfi","insp_mk5i7ehnny043q","insp_mk5gjxwd9cctni","insp_mk5hakhqwlliaj","insp_mix7dlww9f6uy0","insp_mivliwpzyf9flq","insp_mknvm39c70nped","insp_mkh1fj7i2w7jdi","insp_mhada1hxgw8jrc"],
  "mygif-tease-implied": ["insp_miq44cdia88o0q","insp_mizky9lrt5qnc5","insp_miq3h65dhlhxdh","insp_mh1sfhf884ygcc","insp_mix8axa23qy05l","insp_4925af058b14f44f","insp_mgxnzivvau14k2","insp_miq47k80mho23u","insp_miyhuc3u1ylrjf","insp_mhrpl0a6edkr0t","insp_mlaxoohz2ufmm7","insp_3e0608c779cd51ee","insp_miq3tcnqrfjgu1","insp_c51dc788e6081c52","insp_moofd4s5w85gtu","insp_mottgqwxblyvtk","insp_miyny0ht1f1rgp","insp_mlaxt8l174e3h4","insp_mlaxfgpid5yeho","insp_miq37pz39asgy6","insp_mj1g96n1043dzt","insp_miygnmj6smonjc","insp_moofbth5frr07x","insp_miyo34x2pk6nyb","insp_moofe93b5k4vf4","insp_mhrp3xqo2gcp67","insp_mp9q8s0ab60jap","insp_miynohhveirgdx"],
  "mygif-intimate-closeup": ["insp_mozc0ujhqp7mg2","insp_mkqme6mhssv41s","insp_mpc5m3ryp055z8","insp_misdsvfofrbvnv","insp_mhrpteeer511yp","insp_mny31s6l06pfib","insp_mkwqskve4ontyu","insp_miv5k6bls8td0h","insp_mlme5ahemiqsjt","insp_mpc5n8arn1675x","insp_mp6kte1zm7ah4o","insp_mi03mfa7y0jqvl","insp_mivlt80di3tix7","insp_milnd2dj08hnf5","insp_mooff081egvoem","insp_mix7q34lhzx80x","insp_millqunit0ywwj","insp_mjtvb0uen9po7h","insp_mknvo5asba90bi","insp_mknvonxw1e21ev"],
  "mygif-soft-selfie": ["insp_mn90biscb4zg9t"],
  "mygif-outfit-seasonal": ["insp_mq5aocz3b49a2y"],
}
